### ISSUE TITLE
"RpcError: missing response content type", but does it have to be there?

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#102]
I don't know if this is a problem with this library or not.

I am building my backend server and I have the grpc route like this:

```js
const router = new Router()

const routes = [
  router.Middleware(checkIfAuthenticated(IfNotReturn401())),
  router.Post("/api*", grpcWebServer())
]
```

When a request comes, the authentication middleware takes care of figuring out whether to proceed or not and if NOT it issues a response with a 401 status **WITHOUT** `content-type` header:

```
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: Deny
date: Thu, 15 Apr 2021 11:52:53 GMT
content-length: 0
connection: close
```

But now I get this error:

```
RpcError: missing response content type
  at parseFormat (http://localhost:6000/node_modules/.vite/@protobuf-ts_grpcweb-transport.js?v=16e233eb:190:13)
  at readGrpcWebResponseHeader (http://localhost:6000/node_modules/.vite/@protobuf-ts_grpcweb-transport.js?v=16e233eb:116:51)
  at readGrpcWebResponseHeader (http://localhost:6000/node_modules/.vite/@protobuf-ts_grpcweb-transport.js?v=16e233eb:109:12)
  at http://localhost:6000/node_modules/.vite/@protobuf-ts_grpcweb-transport.js?v=16e233eb:373:34
```

Is this correct or should we handle this cases in `parseFormat()`?

**Comment by timostamm** [comment]
gRPC-web transport should detect HTTP 401 and raise a GrpcError UNAUTHENTICATED.  It should not fall on its face because of the omitted header in this case.

**Comment by timostamm** [comment]
Thanks for the bug report, @frederikhors !

Fix is published in v2.0.0-alpha.20, available in the "next" channel.

Could you verify if this fixes the problem?

**Comment by frederikhors** [comment]
I'll check immediately.

I love you and `protobuf-ts` immensely!

**Comment by frederikhors** [comment]
It works!!!!! Thanks! ❤️
