### ISSUE TITLE
Generate purely typescript interfaces / plain JSON representation

### ISSUE THREAD

**Issue by Bluskript** [timostamm/protobuf-ts#111]
Unfortunately, discussions aren't available for this repo and i'm not sure if this feature is out of scope or not.

Basically, I noticed that for large protocols, protobuf bundle size can go to upwards of 50kB. Considering that JSON serialization/deserialization is also accelerated by the browser's native code, I feel like it may be more beneficial for us to use purely the JSON representation of the protobuf for RPCs.

Is it possible for `protobuf-ts` to support generating exclusively typescript interfaces and using `JSON.parse` / `JSON.stringify` for serialization? This could significantly lower bundle size for web apps.

**Comment by frederikhors** [comment]
Can you please post a `.proto`? An example...

This is a great opportunity to understand more. Thank you!

**Comment by Bluskript** [comment]
This is 115KB uncompressed, 25KB compressed. With JSON there wouldn't be any runtime cost since the objects would be directly stringified and parsed with builtin APIs. https://github.com/harmony-development/harmony-web-sdk

**Comment by timostamm** [comment]
Looks like descriptor.ts still contains speed optimized code. That's because descriptor.proto set the file option to optimize for speed. Setting plugin parameter `force_optimize_code_size` should override this.

**Comment by timostamm** [comment]
There are several problems with the JSON approach. I know because [I tried](https://www.npmjs.com/package/protoc-h1-plugins). 

I know, it sounds like a perfect idea. Just do RPC with JSON, and generate TypeScript interfaces (which don't eat up code size at all) for the JSON representation. 

Unfortunately, the protobuf JSON format is not suited well for this. The main issue is that default values are omitted. For example:

```proto
message Example {
   bool bool_field = 1;
}
```

If you create an instance of message and set `boolField = false`, the JSON representation of this message is: 

```
{}
```

This means the interface needs to have "bool_field" typed `boolField: boolean | undefined`. It really is a bad experience working with that. 

Many protobuf implementations have an option to emit default values, but not all (PHP). There are more issues, like oneofs and floats. So I abandoned the idea.

JSON serialization is fast, but at least for reading, binary should actually still be faster. And don't forget that binary format takes only a fraction of the JSON size in many situation, so you loose a bit in code size, but gain in reduced traffic.

**Comment by timostamm** [comment]
I do have an idea to reduce code size further. At the moment, all functionality is packed into `MessageType` and can't be shaken off if you don't need it. 

Moving the methods to standalone functions would mean that webpack output for example would not contain code for the JSON format if you only use the binary format. 

This opens up several design questions though. I think this might be thing for v3...

**Comment by Bluskript** [comment]
another thing I was thinking of was maybe using a metaprogramming approach... possibly an intermediate JSON format that describes the methods and messages in a proto file, which then dynamically generates classes at runtime, while providing typescript definitions only at devtime... although I can imagine this feeling quite flaky.

**Comment by timostamm** [comment]
This is actually already available! At least the core functionality. It is not documented and the API is not streamlined at all, but it works.

```ts
import { Interpreter } from '@protobuf-ts/plugin/build/interpreter';
import { DescriptorRegistry, FileDescriptorSet } from '@protobuf-ts/plugin-framework';
import { LongType, ScalarType, UnknownMessage } from '@protobuf-ts/runtime';
import { readFileSync } from 'fs';

// for the input, we need file descriptors:
// you can generate a file descriptor set with: protoc msg-scalar.proto --descriptor_set_out msg-scalar.bin
// or write them by hand in the JSON format
const buffer = readFileSync("./msg-scalar.bin");

// we need a descriptor registry:
const fileDescriptorSet = FileDescriptorSet.fromBinary(buffer);
const registry = DescriptorRegistry.createFrom(fileDescriptorSet.file[0]);

// now we create the interpreter.
// it can create message types dynamically from the descriptors in the registry.
const interpreter = new Interpreter(registry, {
    normalLongType: LongType.STRING,
    oneofKindDiscriminator: 'oneofKind',
    synthesizeEnumZeroValue: 'UNSPECIFIED$',
});


// this is how you get a dynamic message type
const fooType = interpreter.getMessageType('spec.ScalarValuesMessage');

// you can use it just like the generated messsage types,
// but of course there will be no interface for the message available.
// there is a special type for those messages, the `UnknownMessage`:
const foo: UnknownMessage = fooType.create();

// you can use reflection to work with the message
for (let field of fooType.fields) {
    console.log("field:", field.name, "value:", foo[field.localName]);
    if (field.kind === 'scalar' && field.T === ScalarType.INT32) {
        foo[field.localName] = 123;
    }
}

// you can use all message type methods:
const json = fooType.toJsonString(foo);
console.log(json)
```

This means it is possible to create something like proto-loader with protobuf-ts. There just needs to be a piece of code that reads proto loader json files and turns them into file descriptors.
