### ISSUE TITLE
Twirp server?

### ISSUE THREAD

**Issue by delaneyj** [timostamm/protobuf-ts#116]
I use and :heart: protobuf-ts for a TS twirp client talking to a Go Twirp server.  How much of a lift is it to be able to generate a `twirp server` like you are doing for gRPC?

**Comment by fenos** [comment]
@delaneyj here is the [Twirp Server](https://github.com/hopin-team/twirp-ts) implementation,
I'm very interested to make that work with protobuf-ts too, stay tuned

**Comment by fenos** [comment]
The [Twirp Server](https://github.com/hopin-team/twirp-ts) is now supporting `protobuf-ts` message definitions!

**Comment by timostamm** [comment]
Added to the features list in the readme and mentioned in the manual.
