### ISSUE TITLE
Official Release for protobuf-ts 2.0

### ISSUE THREAD

**Issue by fenos** [timostamm/protobuf-ts#118]
Hi there!

I'm the creator of the [Twirp Typescript](https://github.com/hopin-team/twirp-ts) implementation, I can't believe I just came across to **protobuf-ts**.

**twirp-ts** is currently based on [ts-proto](https://github.com/stephenh/ts-proto), however, after having played around with **protobuf-ts** I can clearly see that it addresses few glitches I had with **ts-proto** and overall seems way more solid.

I've made up my mind and I'd like to switch or at least support **protobuf-ts**

Is there any rough ETA on when the stable v2.0 is going to be available?
Do you think there will be any potential breaking changes before 2.0?

Thanks, and very well done with this.

**Comment by fenos** [comment]
The [Twirp Server](https://github.com/hopin-team/twirp-ts) is now supporting `protobuf-ts` message definitions!

**Comment by timostamm** [comment]
It was about time for a TypeScript Twirp server, nice work!

I've just updated the [milestone](https://github.com/timostamm/protobuf-ts/milestone/1) for 2.0 and set a due date for end of july.

**Comment by timostamm** [comment]
Other issues came up and #62 and #99 are still pending for [Release 2.0](https://github.com/timostamm/protobuf-ts/milestone/1). Moving Milestone due date back 1 week.

**Comment by timostamm** [comment]
:sparkles: [2.0.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.0.0) has been released :sparkles:

Thanks for all the feedback and contributions.
