### ISSUE TITLE
Can't get response headers

### ISSUE THREAD

**Issue by originswift-sys** [timostamm/protobuf-ts#121]
According to the docs, I should be able to extract response headers with something like this:
```ts
const client = new IdentityServiceClient(
  new GrpcWebFetchTransport({
    format: "binary",
  })
);

try {
  const call = client.someMethod({});
  console.log("HEADERS =>", call.trailers);
  console.log("RESPONSE =>", call.response);
} catch (error) {
  console.log(JSON.stringify(error))
}
```
...but it's not working. An `RpcError` object is ALWAYS thrown and I can't get access to the response header, particularly `grpc-status-details-bin` which I need to parse to obtain error details.

**Comment by timostamm** [comment]
I assume you are running the client in a browser? The chat example uses a custom header "x-token":

https://github.com/timostamm/protobuf-ts/blob/17619665a374d6f44962ba0b6f094637f7026c2e/packages/example-chat-system/browser-client/index.ts#L31

Envoy has to be told to allow this header:
https://github.com/timostamm/protobuf-ts/blob/17619665a374d6f44962ba0b6f094637f7026c2e/packages/example-chat-system/server/envoy.yaml#L32

In dotnet: 

https://github.com/timostamm/protobuf-ts/blob/17619665a374d6f44962ba0b6f094637f7026c2e/packages/example-dotnet-grpcweb-server/Startup.cs#L27-L32

This is a CORS issue. You have to set the response header `Access-Control-Allow-Headers` whitelisting the headers you want to grant the browser access to. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers).

Is the `RpcError` or the browser developer tools / network tab giving you any hint about CORS? If not, this might be a different issue.

**Comment by originswift-sys** [comment]
@timostamm I'm using GRPC-Web on dotnet. Envoy isn't part of the mix.
I can see the `grpc-status-details-bin` header on the network tab, which means my setup sends the headers correctly.
As my demo code implies, `RpcError` just takes over, no matter if I'm simply awaiting headers and not response.

**Comment by timostamm** [comment]
Would you kindly share error message, stack, request and response headers?

**Comment by originswift-sys** [comment]
@timostamm Nevermind. I was generating clients with plugin 2.0 and consuming with transport 1.0. Everything is fine after fixing the version mismatch. Thanks for the prompt response and wonderful library.
