### ISSUE TITLE
Is there a way to remove the JSON-related functionality?

### ISSUE THREAD

**Issue by ovidiucp** [timostamm/protobuf-ts#122]
First of all, thanks for this great library!

I'd like to be remove all introspection facilities from the generated code, and leave only the binary format. The ts-proto library has an option for doing this, by passing `--ts_proto_opt=outputJsonMethods=false`. I briefly looked at the protobuf-ts code and I didn't see anything that addresses this.

I specifically want to eliminate from the generated code all references to the proto names, their fields etc. so that it's harder for a potential attacker to reverse engineer the data format used on the wire.

The code responsible for this is in `packages/plugin/src/code-gen/message-type-generator.ts`. For each proto message type generates 

```class <T>$Type extends MessageType$<T>
  constructor() {
    super("message name", [
      // array of fields
    ]);
```

Can we have a command line flag that disables the code generation of the call to `super()`? The reflection and JSON functionalities will obviously no longer work, but for applications that don't need this it should be fine.

Am I missing somethig?

**Comment by timostamm** [comment]
Just omitting `super()` is not enough. The binary methods rely on `create()`, which uses reflection information too (pretty much everything is based on reflection information). Either way, this would break the `IMessageType` contract, which I really don't want to do.

A separate plugin that only generates `readMyMessage()` and `writeMeMessage()` functions would be the way to go, I think.
