### ISSUE TITLE
The link for client style in MANUAL is wrong

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#127]
In MANUAL.MD I can read:

> If you want to use rxjs Observables or plain Promises, you can change the client style for the service.

But [the link for client style](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#rpc-client-styles) is wrong.

**Comment by timostamm** [comment]
Thank you. Client styles have been removed in v2.0.0-alpha.16 to keep the plugin simple. 

I am sure they will come back, but are tabled for now because they obstruct finishing 2.0.
