### ISSUE TITLE
enums as string value

### ISSUE THREAD

**Issue by fenos** [timostamm/protobuf-ts#130]
Hello,

`ts-proto` offers the options `--ts_proto_opt=stringEnums=true` which allows for generated enum types to be string-based instead of int-based.

This is useful if you want "only types" and are using a gRPC REST Gateway configured to serialize enums as strings.

Are you willing to support this? It will be very useful in a twirp and gPRC gateway setting

**Comment by timostamm** [comment]
Hi @fenos, thanks for the feedback. 

Your argument is that it would be more convenient for the mapping layer to work with string enums instead of regular enums? But that would mean that the mapping layer requires the plugin option `stringEnums=true` to be set in order to work correctly. 

I'm not convinced it is good design to require the user to adjust settings to make something work. I think the mapping layer should work out of the box with whatever options the user chooses for their concern. Am I missing the point or does this make sense? 

REST mapping is very interesting and it should be rather easy to implement, I just haven't had time to explore that. #101 asked about it. Do you use REST mapping already? https://github.com/grpc-ecosystem/grpc-gateway ?

**Comment by fenos** [comment]
Hi @timostamm thanks a lot for the answer!

Exactly, it is more convenient for consumers to work with. When a developer reads an OpenAPI documentation which is generated from a protobuf file, it could be much nicer to present the enum as a string instead of having to manually document what the enum `2` is for.


I totally understand your point of not being a good design to enable or disable a flag in order dictate a different behaviour from the standard.
  
However, here is my proposal that I believe, can achieve this functionality in a much cleaner way.

Since this functionality is only useful within a JSON environment, I suggest adding an option in the 2 functions `fromJson` and `toJson` to allow enums as strings.

```ts

SomeProto.fromJson({ enumValue: "PENDING" }, { enumAsString: true })

SomeProto.toJson({ enumValue: 2 }, { enumAsString: true }) // returns enum as string
```

This will result `fromJson` to hydrate the proto object correctly and the `toJson` to return the enum as string to keep consistency.

the `grpc-gateway` works in the same fashion! They have a `JsonMarshaller` which allows both options.

I'd be very keen to this feature

**Comment by timostamm** [comment]
Give it a try, this already works :grin:

The canonical mapping for a protobuf enum is string, and parsers must accept both enum names and integer values. 

The canonical mapping deals with edge cases like numeric map keys, infinite numbers, etc. The documentation is sparse, but the conformance tests are not (protobuf-ts passes them). You can be pretty sure that you'll have perfect JSON interoperability.

**Comment by fenos** [comment]
OMG! I didn't know that!

I'll give it a try right now!

However, we still need to add the option ` { enumAsString: true }` in the `toJson` function am I right?
Or will it handle it automatically as well?

**Comment by fenos** [comment]
Wow!
It works out of the box!

This toolset never disappointed me once. 
It is sooo good.

Well done @timostamm keep up the good work

**Comment by fenos** [comment]
Hi @timostamm I've done some on my twirp server and I believe we should reconsider the `stringEnums` flag for JSON encoding / decoding.

In essence, I have the following enum:

```proto
enum WorkflowStatus {
  WORKFLOW_STATUS_UNKNOWN = 0;
  WORKFLOW_STATUS_PENDING = 1;
  WORKFLOW_STATUS_IN_PROGRESS = 2;
  WORKFLOW_STATUS_FINISHED = 3;
  WORKFLOW_STATUS_ERRORED = 4;
}
```

the JSON spec will of course accept `WORKFLOW_STATUS_PENDING` as a string while encoding and decoding.

However what I'd like to achieve is to be able to accept `PENDING` and return `PENDING` without the prefix `WORKFLOW_STATUS_` the same way the `enum` is converted in `Typescript`

**Comment by timostamm** [comment]
Is that part of a spec or is this your idea? 

I totally agree that enum name restrictions are annoying, but if you change the JSON serialization behavior, this will be incompatible with every other protobuf implementation out there, and that interoperability is the main feature of protobuf.

**Comment by fenos** [comment]
@timostamm I gave more and more thoughts around this.

I think you are 100% right here, it all boils down to how enums works in protobuf.

For now I'll accept the fact that they are annoying 😄  as a workaround I've nested my enum to prevent collisions:

```proto

message Workflow {
  enum Status {
    UNKNOWN = 0;
    PENDING = 1;
    IN_PROGRESS = 2;
    FINISHED = 3;
    ERRORED = 4;
  }
}

```
