### ISSUE TITLE
Do you think this can work with drpc too?

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#132]
Do you think this can work with https://github.com/storj/drpc too?

**Comment by timostamm** [comment]
RPC in protobuf is not specific to gRPC. And gRPC could theoretically also be used with other serialization mechanisms. If drpc is written with that in mind, then yes, protobuf-ts can work with drpc too.

**Comment by frederikhors** [comment]
It would be amazing to have these info on the manual. Can we reopen this until then (i will try this in the next few days).

**Comment by timostamm** [comment]
You mean that protobuf RCP doesn't depend on gRPC? Or drpc specifically?

**Comment by frederikhors** [comment]
I would like to use protobuf-ts with drpc directly.

@zeebo [is working hard](https://github.com/storj/drpc/issues/6#issuecomment-882668698) to make this possible.

**Comment by frederikhors** [comment]
It would be amazing to have in MANUAL instructions like for twirp or grpc-web.

**Comment by timostamm** [comment]
The README.md has links to the twirp, grpc-web, grpc sections in the MANUAL.md.  
Once drpc has support, it can have its own section. 

If you have an idea to surface the features in a better way, let me know. I think a docusaurus page would help, with a better navigation than the markdown manual.

**Comment by frederikhors** [comment]
I think that for now the manual.md is excellent. Docusaurus means a lot of work for what? Infos in clickable pages?

I think the informations for this project at least for now can stay that way.

As soon as I know something about drpc I'll write to you here.
