### ISSUE TITLE
@protobuf-ts/grpc-transport & @grpc/grpc-js dependency

### ISSUE THREAD

**Issue by hugebdu** [timostamm/protobuf-ts#136]
`@grpc/grpc-js` is a [direct dependency](https://github.com/timostamm/protobuf-ts/blob/master/packages/grpc-transport/package.json#L37) of `@protobuf-ts/grpc-transport`, however in order to initialise `GrpcTransport` one [must provide](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#grpc-transport) instance of `ChannelCredentials` from `@grpc/grpc-js` package — that means one must have it as its own dependency.
In case of versions mismatch [this `instanceof` check](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel.ts#L171-L175) fails.

I can think of several options to overcome:
- `@protobuf-ts/grpc-transport` must declare `@grpc/grpc-js` as [peer dependency](https://nodejs.org/es/blog/npm/peer-dependencies/)
- `@protobuf-ts/grpc-transport` will re-export `@grpc/grpc-js`
- `@protobuf-ts/grpc-transport` will provide some factory for channel credentials

cc @ghaiklor-wix @Oleksiika

**Comment by timostamm** [comment]
Thanks for the report, @hugebdu. Ran into that problem a while ago but forgot, TBH.

Peer dependency is the way to go.

**Comment by timostamm** [comment]
Updated `@protobuf-ts/grpc-transport` and `@protobuf-ts/grpc-backend` to specify `@grpc/grpc-js` as a `peerDependency` instead of `dependency`. 

Published in v2.0.0-alpha.29 in the "next" channel.
