### ISSUE TITLE
Support TS 4.3 `noImplicitOverride` compiler flag

### ISSUE THREAD

**Issue by ghaiklor-wix** [timostamm/protobuf-ts#139]
TypeScript recently added a `noImplicitOverride` flag to their configuration. This flag protects from:

> When working with classes which use inheritance, it’s possible for a sub-class to get “out of sync” with the functions it overloads when they are renamed in the base class.

It could be a minor but great addition to the protobuf-ts so it generates code with the `override` keyword to explicitly state that the method overrides another one from the base class.

Thoughts?

**Comment by timostamm** [comment]
That's a nice addition. Birthed by C#, I'd wager.

It appears to be available since 4.3, protobuf-ts is still using 3.9. Updating is a breaking change. Does TypeScript have support timelines so we can determine a good point in time to break?

**Comment by ghaiklor-wix** [comment]
> Birthed by C#, I'd wager

Sure, thanks to papa Anders Hejlsberg 😸 

> Does TypeScript have support timelines so we can determine a good point in time to break?

I'm not sure it even had before or planning to. These versions are not semantic versions, but just an increment. So, as I see it, there are no LTS versions or something like this.

What we could do, actually, is specify `typescript` as part of a peer dependency here. `protobuf-ts` is totally built around TypeScript and having no `typescript` package on the peer side seems off. So we could say "hey, we have protobuf-ts version X that require typescript version Z, please do so".

**Comment by timostamm** [comment]
You're right about TypeScript not following SemVer. Pretty much every minor release includes some [breaking changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#breaking-changes). :raised_eyebrow:

Opening separate issue for peer dependency.

**Comment by timostamm** [comment]
Regarding `noImplicitOverride`: I presume the generated code produces errors on TypeScript 4.3 if the flag is on? That would have to be fixed.

We could generate a `@ts-ignore` annotation with an explanatory comment so we can still support TypeScript < 4.3.

**Comment by ghaiklor-wix** [comment]
> I presume the generated code produces errors on TypeScript 4.3 if the flag is on? That would have to be fixed.

Yeap, that's what is happening in our case. We want to make sure that `override` keyword is used for our codebase, but it breaks the build when building with the protobuf-ts code.

> We could generate a @ts-ignore annotation with an explanatory comment so we can still support TypeScript < 4.3.

Better to use `@ts-expect-error` (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments). That way, if something will change and error is no longer, it will be a compilation error.

But, I'm not sure if that will work great with different compiler combinations. E.g. having `override` keyword in the code base that is being built by `tsc < 4.3` will be a syntax error. I'm not sure `@ts-ignore` or `@ts-expect-error` will help here. Anyway, seems like we could just try to add `override` or `@ts-expect-error` and see how it goes.

**Comment by timostamm** [comment]
> We want to make sure that `override` keyword is used for our codebase, but it breaks the build when building with the protobuf-ts code.

Got it. That needs support.

Until protobuf-ts moves to TypeScript 4 (internally and for generated code), an annotation to ignore errors on TS 4 has to be generated. `@ts-expect-error` is not suitable because it will raise an error if the expected error is not raised.

**Comment by timostamm** [comment]
Sorry for the long wait. https://github.com/timostamm/protobuf-ts/commit/ea11acf5d75d0faba72ac16899768b1a354069e9 adds a new plugin option:

> - "ts_nocheck"
>  Generate a @ts-nocheck annotation at the top of each file. This will become the 
>  default behaviour in the next major release.

This will let the TypeScript compiler ignore the missing `override` keywords and while I'm not super happy about it, it is an appropriate fix for this issue considering that there will likely be other similar cases in the future.

I'll close this issue when it is released.

**Comment by timostamm** [comment]
Released as [v2.2.0-alpha.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.2.0-alpha.0) in the `next` channel.

**Comment by Zamiell** [comment]
Now that TypeScript is a peer dependency, can we reopen this and fix overrides properly without using @ts-ignore?

**Comment by Zamiell** [comment]
> It is not possible to add 'override' with the version of typescript that does not support them.

Right, but if I do have a peer dep of TypeScript that does support them, the `overrides` keywords still do not appear. Thus, I believe this issue should be reopened.

**Comment by timostamm** [comment]
The plugin has a direct dependency on TS 3.9. The compiler API had breaking changes between 3.9 and 4.x. You can't generate "override" statements with 3.9.

**Comment by Zamiell** [comment]
I see. Is there an issue that tracks the status of moving this project off of TS 3.9?

**Comment by timostamm** [comment]
Quoting from an [article on etiquette in OSS](https://teejeetech.medium.com/etiquette-in-open-source-projects-f302b6e19c38):

> Avoid asking for ETAs for issues and feature requests. It’s more rude than you may realize. People working on open-source projects are not your employees. They have no obligation to implement every feature you request, to fix every issue you report, or to provide technical support that you are not even paying for. 

If you want something, try contributing.
