### ISSUE TITLE
Add `typescript` as a peer dependency of `@protobuf-ts/plugin`

### ISSUE THREAD

**Issue by timostamm** [timostamm/protobuf-ts#140]
What we could do, actually, is specify `typescript` as part of a peer dependency here. `protobuf-ts` is totally built around TypeScript and having no `typescript` package on the peer side seems off. So we could say "hey, we have protobuf-ts version X that require typescript version Z, please do so".

_Originally posted by @ghaiklor-wix in https://github.com/timostamm/protobuf-ts/issues/139#issuecomment-892692692_

**Comment by timostamm** [comment]
I don't think any of the runtime packages should have a `typescript` dependency (they could be used with vanilla JS or some other dialect), but `@protobuf-ts/plugin` should be considered. You can't use the generated code without TypeScript, and a peer dependency could declare TypeScript version compatibility. 

Users would typically have `typescript` as a `devDependency` though. I'm not sure how `@protobuf-ts/plugin` having a `peerDependency` on `typescript` works out in this case. This has to be investigated before we can add the peer dependency.

**Comment by ghaiklor-wix** [comment]
> Users would typically have `typescript` as a `devDependency` though. I'm not sure how `@protobuf-ts/plugin` having a `peerDependency` on `typescript` works out in this case. This has to be investigated before we can add the peer dependency.

`peerDependency` is just a metadata for the package managers and there are no conflicts between `dependencies` and `peerDependencies`.

Moreover, different package managers behave differently. E.g. npm v6 does not install the peer dependency automatically, but emits a warning in the console. pnpm has a flag `--strict-peer-dependencies` that throws an error if users have no satisfied peer dependencies (they must add them in their package.json).

So, what I'm trying to say is `peerDependencies` is just a metadata from you, as an author, that says "I don't need it actually right here and now, but I need it later on your side". (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies)

We could set a `typescript` version range, the minimal `typescript` version that is need for your code to build. E.g.

```json
{
  "peerDependencies": {
    "typescript": ">= 3.9"
  }
}
```

**Comment by timostamm** [comment]
Agree with that, but am still not sure how peer dependency plays out :grin: 

I did a test with npm 7.4.0 (which does install peer dependencies by default).

With `@protobuf-ts/plugin` as a `dependency`, `npm i --production` installs `typescript` along with the plugin. With the plugin as `devDependency`, `npm i --production` installs nothing.

Seems very reasonable.

npm 7.4.0 does not complain at all if the user already has a dependency on a TypeScript version that is incompatible with the peer dependency. Not even with `--strict-peer-deps`.

Seems very odd. Pretty much contradicts what [this blog entry](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) says. I'd chalk that up as a npm thing though.

**Comment by timostamm** [comment]
Released in 2.0.1.
