### ISSUE TITLE
README.me use node-protoc in example

### ISSUE THREAD

**Issue by sachaw** [timostamm/protobuf-ts#145]
After some issues with yarn 2 and using the original protoc npm package I rewrote it as:
https://github.com/sachaw/node-protoc
https://www.npmjs.com/package/node-protoc
has almost identical functionality but works on more platforms/package managers now.

If you find any value in it, you could include it in the quickstart section of the readme.

**Comment by timostamm** [comment]
Nice. I'll be adding support for Yarn 2 when it is released. Added a note and a recommendation to use your package for Yarn berry.
