### ISSUE TITLE
Add support for gzip compression

### ISSUE THREAD

**Issue by arontsang** [timostamm/protobuf-ts#153]
At present, there is no way to change the binary message before it is sent on the wire (in an extensible way), this makes it impossible to have plug in compressors, like gzip.

https://github.com/grpc/grpc/blob/master/doc/compression.md

**Comment by timostamm** [comment]
For gRPC-web and Twirp, this is fine. The browser will negotiate the content encoding with the backend.

Is this about gRPC via @grpc/grpc-js?

**Comment by arontsang** [comment]
That would only work with the server->client messaged, client server wouldn't be compressed.

**Comment by timostamm** [comment]
That's true, but neither [Twirp](https://github.com/twitchtv/twirp/blob/main/PROTOCOL.md) nor [gRPC-web](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#compression) specify a mechanism for request compression. I'm also not aware of a browser API that gives us compression. 

If you have a good idea to handle this, I'd say it should be added to the twirp / grpc-web transports.

**Comment by arontsang** [comment]
Grpc supports per message compression, which would actually solve the
problem on the protocol side rather than the transport side.

**Comment by timostamm** [comment]
Yes. Everything gRPC is run by @grpc/grpc-js, we're just generating simple clients that delegate to the runtime library. So this would be a job for @grpc/grpc-js. It's a nice library, written in TypeScript.

Closing this. Please reopen if you think something should be done on Twirp or gRPC-web.
