### ISSUE TITLE
internalBinaryRead does not merge maps correctly

### ISSUE THREAD

**Issue by john-livelyvideo** [timostamm/protobuf-ts#172]
merge() doesn't work right either

Not only should the map get merged, via the keys, the nested messages in the values should also get merged.  What I'm experiencing right now is complete replacement of the value side of the map, when value is a protobuf message.

**Comment by john-livelyvideo** [comment]
val = TRoom.internalBinaryRead(reader, reader.uint32(), options);

there should be a check to see if 'val' already exists at 'key'

            case 2:
                  if(map[key]) {
                    val = map[key];
                    val = TRoom.internalBinaryRead(reader, reader.uint32(), options, val);
                 } else {
                   val = TRoom.internalBinaryRead(reader, reader.uint32(), options);
                }
                break;

**Comment by john-livelyvideo** [comment]
I'm not familiar w/ the codegen framework, but looks like this is the place to change?

https://github.com/timostamm/protobuf-ts/blob/16ce40d32df2f847692543c83cff13bc80d6eece/packages/plugin/src/message-type-extensions/internal-binary-read.ts#L716

**Comment by john-livelyvideo** [comment]
Absolutely, the use case is for supporting delta/snapshot values when implementing event sourcing patterns.  Having the nested maps merge correctly is a very power tool when merging deltas into a snapshot value.

Yes, I was referring to mergePartial.

**Comment by john-livelyvideo** [comment]
import {TChalkcastEventType, TRoot} from "../../protocol.buffer.demo.schema/protos/typescript/chalkcast";
import {natsFormatUuid} from "../../common/helpers/kafkaNats";
import {BinaryReader, BinaryWriter, MessageType} from "@protobuf-ts/runtime";
import {klogInfo} from "../../common/helpers/klogInfo";

const roomId = natsFormatUuid();
const participantId = natsFormatUuid();
const participantId2 = natsFormatUuid();

// back end snapshot image
const serverSnapshot: TRoot = {};

// front end snapshot image
const clientSnapshot: TRoot = {};

// client side delta, egress, published
const delta_0: TRoot = {
    chalkCast: {
        rooms: {
            [roomId]: {
                roomId: roomId,
                participants: {
                    [participantId2]: {
                        participantId: participantId2,
                        handRaised: true
                    }
                }
            }
        }
    }
};

// client side delta, egress, published

const buffer_0 = TRoot.toBinary(delta_0);

const delta_1: TRoot = {
    chalkCast: {
        rooms: {
            [roomId]: {
                roomId: roomId,
                participants: {
                    [participantId]: {
                        participantId: participantId,
                        age: 30
                    }
                }
            }
        }
    }
};

const buffer_1 = TRoot.toBinary(delta_1);

const root = TRoot.create();

TRoot.internalBinaryRead(new BinaryReader(buffer_0), buffer_0.byteLength, {readerFactory: bytes => new BinaryReader(bytes), readUnknownField: true}, root);
klogInfo(TRoot.toJsonString(root));

TRoot.internalBinaryRead(new BinaryReader(buffer_1), buffer_1.byteLength, {readerFactory: bytes => new BinaryReader(bytes), readUnknownField: true}, root);
klogInfo(TRoot.toJsonString(root));

**Comment by john-livelyvideo** [comment]
Hopefully this will make things clearer.  If internalBinaryRead or mergePartial would merge maps correctly, this sort of thing becomes possible ...

https://gist.github.com/john-livelyvideo/8b5eb075d3220cf65af649a024bd0a8d

**Comment by unicomp21** [comment]
You're right, for internalBinaryRead, can we have a flag or something which changes the default behavior?  Does the event sourcing use case make sense?  What I'm looking for is something similar to a lodash.mergeWith().

**Comment by unicomp21** [comment]
If it would make more sense for me to start maintaining a fork(), I'm open to that idea as well.  This repo is a really really nice implementation of protobuf.

**Comment by unicomp21** [comment]
Yeah, you're right, in the java as well ... map values are replaced.

https://github.com/protocolbuffers/protobuf/blob/d08bc71c96d3dfcea12de3d4efacfbad5d473e44/java/core/src/main/java/com/google/protobuf/MapFieldLite.java#L109-L109

I need to override this behavior, in order to get a fine grained merge, for event sourcing usages.

Hate the idea of forking, but don't think I have a choice?

**Comment by unicomp21** [comment]
Not sure I understand, we're saying I can create my own version of mergePartial() to customize the behavior?
