### ISSUE TITLE
extension points for plugin

### ISSUE THREAD

**Issue by hugebdu** [timostamm/protobuf-ts#183]
Do you have any plans to allow extending the existing plugin? Or maybe it is possible already, and I just couldn't find it...

For example we'd like for each and every proto message to generate builders, test builders (with test values) and probably jest matchers.

Of course we can take the plugin framework and write our own but that means duplicate codegen execution and plenty of code copy & paste from the plugin.

Thanks!

**Comment by timostamm** [comment]
I have never used extension points, but I've heard they might be unpleasant to use. Is it an option to do what you need in runtime?

For example, the existing `reflectionCreate()` takes a `IMessageType<T>` and returns an instance of message `T`, all via reflection ops:

https://github.com/timostamm/protobuf-ts/blob/fbce12b7259cacea5d45ebf3503c8ac8a0200c73/packages/runtime/src/reflection-create.ts#L10

I imagine it should be possible to create a jest matcher like `isMessageOfType(received, type: IMessageType)`, for example.

Could you elaborate a bit what you want to do?

**Comment by hugebdu** [comment]
@timostamm thanks for your reply.
The runtime magic is an option indeed, however the devex isn't great (IDE support and compilation errors are cryptic). Thus I prefer to do a codegen. Currently having some post-codegen with [ts-morph](https://github.com/dsherret/ts-morph).

Another use case I have is message type refinement (due to [custom options](https://developers.google.com/protocol-buffers/docs/proto3#customoptions)) or method signatures (think something like `CallContext` argument).

I was thinking about some [decorators](https://en.wikipedia.org/wiki/Decorator_pattern) support for all those tasty [generators](https://github.com/timostamm/protobuf-ts/tree/master/packages/plugin/src/code-gen) you have there.

Since I couldn't find any programmatic API for the plugin, possible API could be another plugin [parameter](https://github.com/timostamm/protobuf-ts/blob/master/packages/plugin/src/protobufts-plugin.ts#L31) with absolute path to `.js` file with decorators factory:

```
exports = {
  enumGeneratorDecorator: {...},
  methodInfoGeneratorDecorator: {...},
  // etc
}
```

**Comment by timostamm** [comment]
The [plan](https://github.com/timostamm/protobuf-ts/issues/356) is to switch to the base types provided by protobuf-es. protobuf-es includes a much improved plugin framework with [@bufbuild/protoplugin](https://github.com/bufbuild/protobuf-es/tree/main/packages/protoplugin), which makes it a whole lot easier to write your own plugins. 

I think this should be the best way forward for your use case as well (generating builder, test builders, jest matchers). It might not give you all the capability extension points give you, but they are a double edged sword for sure. You can see the code for a simple plugin [here](https://github.com/bufbuild/connect-web/blob/main/packages/protoc-gen-connect-web/src/protoc-gen-connect-web-plugin.ts). I hope we can simplify it even more (not needing to type out .js, .ts and .d.ts code for example).
