### ISSUE TITLE
Add `_pb` or `.pb` suffix to generated filenames

### ISSUE THREAD

**Issue by kriswuollett** [timostamm/protobuf-ts#186]
Currently the generated file with the messages cannot be recognized by filename alone unlike some of the standard generators like for C++ and Python. This can be considered an issue since developers may wish to exclude checkin of generated files like with a `.gitignore` file, or perform automatic analysis on the files. Also there is the issue of accidentally overwriting Typescript source code with the same filename if the protos are kept in separate source tree.

If it is not possible to evolve the default naming scheme, I'd highly recommend adding a plugin option to make the generated file names distinctive. For example, given `kw/admin.proto`, it should generate file names like `kw/admin.pb.ts`, `kw/admin.pb_grpc_client.ts`, and `kw/admin.pb_grpc_server.ts`. 

The `pb_` part informs us that it is generated with `protoc` and `grpc_` for the transport. It's slightly unfortunate that most assume that gRPC always implies Protobuf, but [FlatBuffers](https://google.github.io/flatbuffers/) is also a supported message serialization type... so always having the `pb_` part helps avoiding conflicts depending on the FlatBuffer generator implementation.

**Comment by timostamm** [comment]
I've always found it best to generate into a dedicated directory. But I see your point. It looks like every official code generator for languages that import based on file names to add a `_pb` or `.pb` suffix.

**Comment by timostamm** [comment]
https://github.com/timostamm/protobuf-ts/commit/5e0792557a5614cb0394a9c895c39d6edca509f7 adds a new plugin option:

> - "add_pb_suffix"
  Adds the suffix _pb to the names of all generated files. This will become the 
  default behaviour in the next major release.

I'll close this issue when it is released.

**Comment by timostamm** [comment]
Released as [v2.2.0-alpha.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.2.0-alpha.0) in the `next` channel.

**Comment by kkocdko** [comment]
What about `.pb.ts`?
