### ISSUE TITLE
Babel compatibility

### ISSUE THREAD

**Issue by cortopy** [timostamm/protobuf-ts#188]
I just started using protobuf-ts and I would like to say thank you so much for creating this. The quality of the ts generated is superb.

I managed to migrate one of my calls from [improbable](https://github.com/improbable-eng/grpc-web) to the code generated with the web transport. It transpiles ok.

However, babel seems to get on the way. With the default babel preset, this code:

```ts
class ChatStatusQueryRequest$Type extends MessageType<ChatStatusQueryRequest> {
    constructor() {
        super("support.v1.ChatStatusQueryRequest", []);
    }
}
```

is transformed into:

```js
var ChatStatusQueryRequest$Type = /*#__PURE__*/function (_MessageType) {
  (0,_babel_runtime_helpers_esm_inheritsLoose__WEBPACK_IMPORTED_MODULE_0__["default"])(ChatStatusQueryRequest$Type, _MessageType);

  function ChatStatusQueryRequest$Type() {
    return _MessageType.call(this, "support.v1.ChatStatusQueryRequest", []) || this;
  }

  return ChatStatusQueryRequest$Type;
}(_protobuf_ts_runtime__WEBPACK_IMPORTED_MODULE_1__.MessageType);
``` 

and it doesn't work. As soon as the `super` gets called, the code throws `class constructor MessageType cannot be invoked without 'new'`. This happens regardless of whether optimisation is set for speed or size

I've managed to narrow it down to how babel interprets super calls [here](https://babeljs.io/docs/en/assumptions#superiscallableconstructor).

This option in .babelrc seems to do the trick:

```json
  "assumptions": {
    "superIsCallableConstructor": false
  },
```

And now it works!!!

I just wanted to get some confirmation if this is the right approach. And if its, then I think a few lines to the manual somewhere would be very useful. I can do a PR if it's ok

**Comment by timostamm** [comment]
I have not used Babel for a long time. A class that calls it's super constructor does not seem very extraordinary, so I'm a bit surprised that extra configuration seems to be necessary. 

Babel's docs say:

> When extending classes, assume that the super class is callable. This means that it won't be possible to extend native classes or built-ins, but only compiled classes or ES5 function constructors.

So you should check whether your code base extends `Error` or similar anywhere.
