### ISSUE TITLE
Property x does not exist on type { oneofKind: undefined; }

### ISSUE THREAD

**Issue by zhaytee** [timostamm/protobuf-ts#189]
Hello! protobuf-ts looks great compared to google-protobuf, so I'm giving it a shot. I've got a huge proto API that I'm trying to compile.

The protoc step works fine, but when I go to use the resulting typescript library in a project, tsc fails with some very specific compilation errors regarding "oneof" types. They're all related to `{ oneofKind: undefined; }` being used as part of a type in a lot of places (i.e. with the "or" construct `| { oneofKind: undefined; }`).

Here are a few examples:
```
error TS2339: Property 'anyVal' does not exist on type '{ oneofKind: "anyVal"; anyVal: Any; } | { oneofKind: undefined; }'.
  Property 'anyVal' does not exist on type '{ oneofKind: undefined; }'.

2986             Any.internalBinaryWrite(message.value.anyVal, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
```

```
error TS2339: Property 'string' does not exist on type '{ oneofKind: "string"; string: string; } | { oneofKind: undefined; }'.
  Property 'string' does not exist on type '{ oneofKind: undefined; }'.

1484             writer.tag(1, WireType.LengthDelimited).string(message.inner.string);
```

It looks like, if the `| { oneofKind: undefined; }` bit weren't present, the type would be satisfied. Is this a known issue? Are there any workarounds?

I'm using protobuf-ts 2.0.7 with TypeScript 4.5.2.

Any help would be appreciated. Thank you!

**Comment by timostamm** [comment]
Hey @zhaytee, there's the following note in the manual:

> Note: you have to turn on the strictNullChecks option in your tsconfig.json for this feature

Do you have this enabled? It should be use useful option for other cases as well. If I remember correctly, it should be enabled if you enable `strict`.

**Comment by zhaytee** [comment]
Hi @timostamm , thank you! I missed that bit. Turning on `strict` mode did indeed do the trick.

**Comment by lucasrabiec** [comment]
@timostamm I have the same issue `Property 'anyVal' does not exist on type '{ oneofKind: "anyVal"; anyVal: Any; } ...`, even if the `strict` and `strictNullChecks` are enabled. How can I handle this?

**Comment by lucasrabiec** [comment]
Ok, nvm. I hadn't noticed that we need to add `if` statement with a check for `oneofKind`.
