### ISSUE TITLE
Add service/method name to RpcError

### ISSUE THREAD

**Issue by jcready** [timostamm/protobuf-ts#195]
When handling/logging errors from a global POV we lose context of what service/method is the source of the `RpcError`. I believe this type of information should be available at every place a new `RpcError` might be instantiated and would be quite useful when handling the errors.

**Comment by timostamm** [comment]
Good point. 

I'd say [RpcError](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/runtime-rpc/src/rpc-error.ts) should have properties for `serviceName` and `methodName` and use them in its `toString` implementation. The names are available through [MethodInfo](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/runtime-rpc/src/reflection-info.ts#L30) in all transports. 

That should be very easy to do in [twirp-transport.ts](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/twirp-transport/src/twirp-transport.ts) and  [grpc-web-transport.ts](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/grpcweb-transport/src/grpc-web-transport.ts). Unfortunately, some functions in [grpc-web-format.ts](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/grpcweb-transport/src/grpc-web-format.ts) and [twirp-format.ts](https://github.com/timostamm/protobuf-ts/blob/468d9c3d00ccbe5cd55b6a1a5a2bbb9ba22c26d5/packages/twirp-transport/src/twirp-format.ts) throw as well.

**Comment by jcready** [comment]
Some questions for implementation:

1. What are your thoughts on simply including the `MethodInfo` on `RpcError` as a property instead of more scoped properties like `serviceName` and `methodName`? It clearly provides more information, but it also increases the surface area and forces us to make the `RpcError` generic to properly type the `MethodInfo<I, O>` or default to the untyped `MethodInfo<any, any>`.
2. The current `RpcError` constructor already takes three arguments. The options we have to add any new property to the `RpcError` are:
   1. Include a forth *optional* argument which then forces the new property to be optional or default to some value that meets the TS type constraint, but can't be reliably consumed (e.g. `this.serviceName = serviceName ?? ''`)
   2. Break the existing constructor contract. Either by inserting the new propert(y/ies) before the `meta` arg or by moving everything but `message` (first arg) into an object as the second arg.
   3. Make the `meta` (third arg) default to `{}` in the constructor which I believe doesn't technically break the contract.
      ```diff
      - constructor(message: string, code = 'UNKNOWN', meta?: RpcMetadata) {
      + constructor(message: string, code = 'UNKNOWN', meta: RpcMetadata = {}, another: any) {
      ```
3. How would you like to solve the issue with some functions in grpc-web-format.ts and twirp-format.ts throwing w/o access to the `MethodInfo`? To me it seems like the options are:
   1. Pass the `MethodInto` into those functions (technically breaks contract since those functions are exported)
   2. Mark those fields as optional + mutable on the `RpcError` and make the consumer(s) of these functions wrap them in try/catch so that *it* can add/set the instance properties on the `RpcError` itself.
   3. Change those functions to return `OriginalReturnValue | RpcError` (breaks contract). This solution also requires 3.i or 3.ii.

**Comment by timostamm** [comment]
1. I think it's fine to use `MethodInfo<any, any>`. But for https://github.com/timostamm/protobuf-ts/issues/164, some refactoring of `MethodInfo` may be necessary, possibly removing the reference to the service. Because of that, I think using simple strings for `serviceName` and `methodName` is preferable.
2. What about not adding a CTOR argument, and setting the properties after creation? It would allow us to make this change in a minor release. 
3. I didn't consider ii., but it looks like this is a great idea... Both grpc-web-transport.ts and twirp-transport.ts already have a catch that makes sure we raise an `RpcError`, and it should be straight-forward to set `serviceName` and `methodName` at this place.

**Comment by timostamm** [comment]
Released as [v2.2.0-alpha.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.2.0-alpha.0) in the `next` channel.

**Comment by jcready** [comment]
Excellent! Is there something holding up an official (non-alpha) release or an E.T.A. for it? I'd like to update but I suspect bumping my stable dependency version (2.1.0) to an alpha version wouldn't pass code review.

**Comment by timostamm** [comment]
v2.2.0 is released :)
