### ISSUE TITLE
Major version bump

### ISSUE THREAD

**Issue by enyo** [timostamm/protobuf-ts#196]
In the changelog you state: "Note: Going forward, protobuf-ts will bump the major version for all releases that add features. Minor releases will be used for releases that only contain bug fixes.". Why?

**Comment by timostamm** [comment]
Ah, my bad. Looks like I didn't have my coffee when I wrote that note. Thanks for the bringing this up. 

In the past, we didn't do minor releases, only patches and major. We added features in patch releases, which should have been minor releases. Going forward, we are going to do minor releases, too. That's it.

**Comment by enyo** [comment]
Ah, that makes more sense :) Thanks.
