### ISSUE TITLE
`server_generic` option stopped working

### ISSUE THREAD

**Issue by sessfeld** [timostamm/protobuf-ts#202]
It seems that in the latest release the `server_generic` option no longer generates any output. The reason for that is line where the options are generated:

https://github.com/timostamm/protobuf-ts/blob/4304289f4ed83f60d9ba5d6b1b55abc48db84d8d/packages/plugin/src/our-options.ts#L307-L309

**Comment by timostamm** [comment]
The fix is released in [v2.2.1](https://github.com/timostamm/protobuf-ts/releases/tag/v2.2.1)
