### ISSUE TITLE
Running on platforms with inofficial protoc builds (e.g. Raspberry Pi)

### ISSUE THREAD

**Issue by dpkay** [timostamm/protobuf-ts#21]
Hi!
I wrote a small home automation tool using protobuf-ts on my Mac, where it works great, and I love the compactness and ease of use of the library. Thank you for writing it!

Now that I'm trying to deploy it to my Raspberry PI (32-bit), I'm running into an issue in that the protobuf owners doesn't seem to be publishing official binaries for that platform. Instead, I use protoc by simply installing the protobuf compiler apt package. I assume this is built by someone else, but seems to work fine. Here is the precise version of protoc that I'm installing that way:

$ file /usr/bin/protoc
/usr/bin/protoc: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked

Sadly, though, protobuf-ts insists on downloading protoc from the release repository, or at least I haven't found a way to circumvent this. Is there an "official" way to do this, or should I find a way to hack around it?

Thanks!
Dominik

**Comment by timostamm** [comment]
Hi Dominik, 

thanks for the feedback. In the latest release, the behaviour of @protobuf-ts/protoc was changed and updating should fix your issue.

1.0.5 (and earlier) tried to install protoc immediately on installation of the package.  
The new version 1.0.6 only tries to install protoc when you run `npx protoc`. 

Could you try updating to the latest version? For example, with:

```shell
npm --depth 2 update @protobuf-ts/plugin
```

Let me know if this works for you. 


Cheers,
Timo

**Comment by timostamm** [comment]
HI @dpkay, closing this one, see above.

If the fix does not work you, please reopen.
