### ISSUE TITLE
Generate .d.ts alone

### ISSUE THREAD

**Issue by alejandroclaro** [timostamm/protobuf-ts#227]
I would like to know if it's possible to build the .d.ts file alone instead of the full typescript code.

**Comment by timostamm** [comment]
Hey @alejandroclaro, with the option `output_javascript`, the plugin emits `.js` files, along with `.d.ts` files.

When this was added, I thought about an option to emit just `.d.ts` but couldn't think of a use case.

Could you explain what you like to use it for? Or are the docs unclear about `.js` always coming with `.d.ts`?

**Comment by alejandroclaro** [comment]
Thanks. I found out that in that way it works.

Not what I'm looking for, but it's ok for now.

I'm replacing other package to use this, since protobuf-ts is better structured by separating the CLI from the runtime library. However, before, I developed a roll-up plugin to process proto files. So it was possible to import the `.proto` directly from any script before bundle it. For typescript code, what I was doing is to generate only the `.d.ts` file during the preparation of the package.

**Comment by timostamm** [comment]
It seems to me that having to generate the typings ahead of time negates any benefit of generating the actual code on demand. Generating only what you need might have some perf benefits in the build process, but that too is probably negated by generating typings separately. 

If build perf is a concern, it is an option to _commit_ generated code, and have CI do generation and fail on a diff.
