### ISSUE TITLE
RpcError: missing trailers

### ISSUE THREAD

**Issue by zpix1** [timostamm/protobuf-ts#232]
Got this error while decrypting messages from gRPC-web akka support (https://doc.akka.io/docs/akka-grpc/current/server/grpc-web.html)
and from envoy. 
```
rpc-error.js:6 Uncaught (in promise) RpcError: missing trailers
    at grpc-web-transport.js:148:1
```
Commenting lines where error is thrown fixes it (grpc-web-transport.js:147-162) and a correct protobuf object is returned
```JS
 .then(() => {
  // if (!maybeTrailer)
  //     throw new RpcError(`missing trailers`, GrpcStatusCode[GrpcStatusCode.DATA_LOSS]);
  // // istanbul ignore if - this should be impossible and only here to satisfy TypeScript
  // if (!maybeStatus)
  //     throw new RpcError(`missing status`, GrpcStatusCode[GrpcStatusCode.INTERNAL]);
  // if (!maybeMessage && maybeStatus.code === 'OK')
  //     throw new RpcError('expected error status', GrpcStatusCode[GrpcStatusCode.DATA_LOSS]);
  // if (!maybeMessage)
  //     throw new RpcError(maybeStatus.detail, maybeStatus.code, maybeTrailer);
  defMessage.resolve(maybeMessage);
  if (maybeStatus.code !== 'OK')
      throw new RpcError(maybeStatus.detail, maybeStatus.code, maybeTrailer);
  defStatus.resolve(maybeStatus);
  defTrailer.resolve(maybeTrailer);
})
```

Not sure if it is ok for grpc-web server/proxy not to send trailers, but maybe there is some option to disable these checks?

Code used to make a request:
```TS
const transport = new GrpcWebFetchTransport({
    baseUrl: 'https://test.com',
    meta: {
        'Authorization': 'Basic ' + Buffer.from(`${login}:${password}`).toString('base64')
    }
});

this.client = new TestServiceClient(transport);
const result = await this.client.test({});
console.log(result);
```

**Comment by timostamm** [comment]
Hey Ivan, this is a bug in grpc-akka: https://github.com/akka/akka-grpc/issues/1465  
It looks like a fix is on the way: https://github.com/akka/akka-grpc/pull/1552

If you can confirm that the fix solves the issue for you, it might be helpful to the grpc-akka folks to tell them about it.

I don't think we should disable trailer checks on our side, so I'm closing this.
