### ISSUE TITLE
Constructor for "Any" type not generated?

### ISSUE THREAD

**Issue by GavinRay97** [timostamm/protobuf-ts#247]
Hello, thanks a ton for this library

I have run into a problem while trying to write a Node.js implementation for Apache Arrow's Flight RPC service
The protobuf files use `bytes` to represent unknown payloads:

https://github.com/apache/arrow/blob/11d2e4863974b95c1fa637e83757b98f291366c3/format/Flight.proto#L232-L236

```proto
  /*
   * Opaque value used to express a command. Should only be defined when
   * type = CMD.
   */
  bytes cmd = 2;
```

These payloads in FlightSQL are expected to be `Any.pack(SomeType)`.

https://github.com/apache/arrow/blob/968e6ea488c939c0e1f2bfe339a5a9ed1aed603e/java/flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java#L128-L138

```java
  public FlightInfo getCatalogs(final CallOption... options) {
    final CommandGetCatalogs.Builder builder = CommandGetCatalogs.newBuilder();
    final FlightDescriptor descriptor = FlightDescriptor.command(Any.pack(builder.build()).toByteArray());
    return client.getInfo(descriptor, options);
  }
```

However, when I ran the generator on the proto files, I didn't get code generated for `Any`.

I tried to do this:

```ts
const service: IFlightService = {
    getFlightInfo: function (call: grpc.ServerUnaryCall<FlightDescriptor, FlightInfo>, callback: grpc.sendUnaryData<FlightInfo>): void {

        if (CommandGetCrossReference.is(CommandGetCrossReference.fromBinary(flightDescriptor.cmd))) {
            const cmd = CommandGetCrossReference.fromBinary(flightDescriptor.cmd);
            console.log("CommandGetCrossReference", cmd);
        }

        if (CommandGetDbSchemas.is(CommandGetDbSchemas.fromBinary(flightDescriptor.cmd))) {
            const cmd = CommandGetDbSchemas.fromBinary(flightDescriptor.cmd);
            console.log("CommandGetDbSchemas", cmd);
        }

        // Etc, repeated for each type
    },
}

client.getFlightInfo({
    path: [],
    type: FlightDescriptor_DescriptorType.CMD,
    cmd: CommandGetTables.toBinary({
        includeSchema: true,
        tableTypes: ["TABLE", "VIEW"],
        catalog: "my-catalog",
    })
});
```

But the issue is that it seems to actually match every type:

```
CommandGetTables {
  tableTypes: [ 'TABLE', 'VIEW' ],
  includeSchema: true,
  catalog: 'my-catalog'
}
CommandGetTableTypes {}
CommandStatementQuery {
  query: 'my-catalog',
  [Symbol(protobuf-ts/unknown)]: [
    { no: 4, wireType: 2, data: <Buffer 05 54 41 42 4c 45> },
    { no: 4, wireType: 2, data: <Buffer 04 56 49 45 57> },
    { no: 5, wireType: 0, data: <Buffer 01> }
  ]
}
```

What should I do here?
Thank you =)

**Comment by timostamm** [comment]
> However, when I ran the generator on the proto files, I didn't get code generated for Any.

Yes, `protobuf-ts` doesn't publish the well-known types, and only generates them if they are within the files to generate. With `protoc`, that means adding `google/protobuf/any.proto` to the argument list. If Any is used anywhere within the proto files you compile, that is not necessary, but in your case, it isn't.

I'd suggest decoding from binary only once:

```ts
const cmdAny = Any.fromBinary(flightDescriptor.cmd);
if (Any.contains(cmdAny, CommandGetTables)) {
   const cmd = Any.unpack(cmdAny, CommandGetTables);
```

But mostly for code style, performance is probably irrelevant here.

Quite the mind-bender to see an Any put into a bytes field :stuck_out_tongue:

**Comment by GavinRay97** [comment]
Ahh I didn't know you could add `google/protobuf/any.proto` directly to the list, that's very useful!

> I'd suggest decoding from binary only once:

This is much better, nice suggestion -- thanks

> Quite the mind-bender to see an Any put into a bytes field 😛

😅
