### ISSUE TITLE
Error when importing generated files

### ISSUE THREAD

**Issue by MirkoLenz** [timostamm/protobuf-ts#251]
Hello,
first of all, thank you for creating this library. I switched away from the official one due to the lack of native JSON import/export.

I am currently building a microservices-based application for research and would like to make the Typescript files generated from my protobuf definitions available on npm (to simplify usage for others). The package is available at <https://www.npmjs.com/package/@recap-utr/arg-services>

When importing the generated interfaces in a React app, I am faced with the following issues:

```
ERROR in ./node_modules/@recap-utr/arg-services/arg_services/graph/v1/graph_pb.ts 5:12
Module parse failed: Unexpected token (5:12)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| // tslint:disable
| // @ts-nocheck
> import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
| import type { IBinaryWriter } from "@protobuf-ts/runtime";
| import { WireType } from "@protobuf-ts/runtime";
```

```
ERROR in ./node_modules/@recap-utr/arg-services/google/protobuf/struct_pb.ts 36:12
Module parse failed: Unexpected token (36:12)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| // OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
| //
> import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
| import type { IBinaryWriter } from "@protobuf-ts/runtime";
| import { WireType } from "@protobuf-ts/runtime";
```

```
ERROR in ./node_modules/@recap-utr/arg-services/google/protobuf/timestamp_pb.ts 36:12
Module parse failed: Unexpected token (36:12)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| // OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
| //
> import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
| import type { IBinaryWriter } from "@protobuf-ts/runtime";
| import { WireType } from "@protobuf-ts/runtime";
```

I am using the newest version of Typescript (4.6.2) and webpack (5.70.0).

I already searched the web for such errors, but was not able to find any other reference to my particular error. As this is the first time I created an npm package (I am more experienced with Python), it may also be an error on my side. In Visual Studio Code however, no error is shown and it only occurs when I start my project with `npm start`. Do you have any clue what could cause this error? Any help/hint would be much appreciated!

**Comment by MirkoLenz** [comment]
I was able to solve the issue by myself and thus have closed this issue.

For anyone that may come across the same error, here is the solution:
If you publish a package to npm, it cannot only contain `.ts` files. Webpack expects plain `.js` files to build the app. Instead, you should provide only the type definitions as `.d.ts` files.

Since I have been using this plugin in its default configuration, all generated files were regular `.ts` files. I mitigated the issue by using the option `output_javascript`. The plugin then outputs both `.js` and `.d.ts` files which can the be directly published to npm.

**Comment by timostamm** [comment]
Hey Mirko, late to the party, just wanted to confirm that `output_javascript` was added exactly for this use case. Before the option was added, publishing to npm was only possible with an intermediate build step.
