### ISSUE TITLE
Is there some possibilities to integrate with grpc-web-devtools or chrome devtools?

### ISSUE THREAD

**Issue by someden** [timostamm/protobuf-ts#252]
I was trying something like this:
```
const transport = new GrpcWebFetchTransport({
  baseUrl: "localhost:3000"
});

const client = new HaberdasheryClient(transport);

const enableDevTools = window.__GRPCWEB_DEVTOOLS__ || (() => {});
enableDevTools([client]);
```
But I've got an error: `TypeError: Cannot read properties of undefined (reading 'rpcCall')`

**Comment by timostamm** [comment]
Hey Denis, 

the chrome extensions is written for the [gRPC-Web Client Runtime Library](https://www.npmjs.com/package/grpc-web) specifically.  It works by adding an interceptor to the client in user-space, then sending request / response data to the extension. This is the relevant script: [content-script.js](https://github.com/SafetyCulture/grpc-web-devtools/blob/404c5b89ba923f42d9553b7c5d2b8aac510a4c26/public/content-script.js)

It looks like it _might_ be possible to piggyback on the extension (if necessary with a proxy gRPC-web client).

On the other hand, you could also add logging statements to a protobuf-ts interceptor, and get a user experience that is very similar to the extensions. The extension requires you to modify your application too.

**Comment by someden** [comment]
Simple example of integration with [grpc-web-devtools](https://github.com/SafetyCulture/grpc-web-devtools):
```js
interceptors: [
  {
    interceptUnary(next, method, input, options) {
      const call = next(method, input, options);

      call.then((finishedUnaryCall) => {
        window.postMessage(
          {
            type: '__GRPCWEB_DEVTOOLS__',
            method: method.name,
            methodType: 'unary',
            request: finishedUnaryCall.request,
            response: finishedUnaryCall.response,
          },
          '*'
        );

        return finishedUnaryCall;
      });

      return call;
    },
  },
],
```

**Comment by someden** [comment]
@timostamm by the way, why implementation of interceptors does not compatible with https://grpc.io/blog/grpc-web-interceptor/

**Comment by timostamm** [comment]
[grpc-web](https://www.npmjs.com/package/grpc-web) interceptors are specific to grpc-web. Our interceptors apply to all transports.
