### ISSUE TITLE
Option to append /* eslint-disable */ in generated files.

### ISSUE THREAD

**Issue by timostamm** [timostamm/protobuf-ts#256]
### Discussed in https://github.com/timostamm/protobuf-ts/discussions/255

<div type='discussions-op-text'>

<sup>Originally posted by **jimmymkude** March 22, 2022</sup>
Hi all,

I find the '// tslint:disable' on top of the generated files very useful and convenient. I was wondering if the same could be for eslint. Appending '/* eslint-disable */' beneath the '// tslint:disable'.</div>

**Comment by galah92** [comment]
Would love that very much as well.

**Comment by timostamm** [comment]
Released in [v2.4.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.4.0).

**Comment by timostamm** [comment]
Thank you, @RyotaSugawara. Fix is released in [v2.5.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.5.0).
