### ISSUE TITLE
Changing dependency behavior for well-known types

### ISSUE THREAD

**Issue by timostamm** [timostamm/protobuf-ts#257]
I'm currently pondering changing a behavior related to well-known types and would like to gather some feedback so we don't break anybodies code.

The issue is: `protobuf-ts` does not maintain [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf), they are always generated on demand. At the same time, plugins are only supposed to generate the files requested to be generated. With `protoc`, that means you have to specify well-known types explicitly as a source. `buf` makes the assumption that all code generators come with their own well-known types in a library, and do not need to be generated.

We have the plugin option `generate_dependencies`, which will sidestep the "rule" that plugins should only generate the files requested, and instead generates all files in the code generator request, including dependencies. This is somewhat of a workaround for the well-known types with `buf`, but isn't ideal because it generates more than users may want.

I'm thinking about changing `protobuf-ts` to always generate well-known types, regardless of the `generate_dependencies`. This will improve integration with `buf`, and the only situation where I could see this changing behavior for users is when they want to generate only a single file, which happens to import a well-known type. In that specific case, `protobuf-ts` will generate a file that it didn't generate before.

Are there any use-cases I'm missing? If not, I'm considering changing the behavior as described in a minor release instead of a major.

**Comment by j-boecker** [comment]
Hello Timo, 
not sure if this is related to the issue. But we currently have a problem with importing well-known types like StringValue or BoolValue. The import path is pointing to a non existing location: 
 `import { StringValue } from "../google/protobuf/wrappers";`

 _Cannot find module '../google/protobuf/wrappers' or its corresponding type declarations.ts(2307)_

Is there a way to also generate the files for google/protobuf/wrappers ?

**Comment by timostamm** [comment]
Yep, that sounds related, and the explanation is up there, but I realize it might be a bit dense to follow.

If you use `protoc`, you should include the argument `google/protobuf/wrappers.proto`, or the plugin option `generate_dependencies`.

If you use `buf`, you should set the plugin option `generate_dependencies`.

If https://github.com/timostamm/protobuf-ts/pull/258 gets merged, you don't need either.

**Comment by timostamm** [comment]
This has been implemented and released in [v2.5.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.5.0)
