### ISSUE TITLE
Arrays are incorrectly marked as mandatory

### ISSUE THREAD

**Issue by Zamiell** [timostamm/protobuf-ts#294]
According to [this StackOverflow question](https://stackoverflow.com/questions/25637687/optional-repeated-with-google-protobuf-for-java), all arrays (e.g. `repeated` elements) in protobuf are optional.

Currently, protobuf-ts does not understand this, and compiles arrays to non-optional properties.
This means that you get TypeScript errors if you try to use an interface without an array specified.

For example:

```proto
message RequestJoinGame {
  optional PortSet server_ports = 4;
  repeated PortSet client_ports = 5;
}
```

Gets compiled to:

```ts
export interface RequestJoinGame {
    serverPorts?: PortSet;
    clientPorts: PortSet[];
}
```

When it should actually be compiled to:

```ts
export interface RequestJoinGame {
    serverPorts?: PortSet;
    clientPorts?: PortSet[];
}
```

**Comment by timostamm** [comment]
The stackoverflow answer is misleading. Repeated fields are always optional in the sense that it's not required to encode any value for them in the binary format.

But that doesn't mean the the generated code shouldn't have a property that's always present, whether the array is empty or not.

If it was `clientPorts?: PortSet[]`, it would be _really_ inconvenient to use. Consider:

```ts
declare var req: RequestJoinGame;
declare var set: PortSet;

req.clientPorts.length; // type error
req.clientPorts.push(set); // type error

// not great:

req.clientPorts?.length;

if (req.clientPorts === undefined) {
  req.clientPorts = [];
}
req.clientPorts.push(set);
```

It is certainly cumbersome to specify `clientPorts: []` every time you want to create a message. But that's what `RequestJoinGame.create()` is for. It takes a `PartialMessage<RequestJoinGame>` as input, where all properties are optional. 

So everything below is valid:

```ts
let req: RequestJoinGame;

req = RequestJoinGame.create();

req = RequestJoinGame.create({});

req = RequestJoinGame.create({
  clientPorts: []
});

req = RequestJoinGame.create({
  clientPorts: [set]
});

req.clientPorts.push(set);
```

**Comment by Zamiell** [comment]
I see. Thank you for the detailed response! I will close this now.
