### ISSUE TITLE
Odd behavior if field name starts with underscore

### ISSUE THREAD

**Issue by jcready** [timostamm/protobuf-ts#303]
I'll preface this by saying this might actually be a bug in `protoc` as the [proto2](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec) and [proto3](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec) specifications forbid field names from starting with an underscore:

```ebnf
|   alternation
{}  repetition (any number of times)
letter = "A" … "Z" | "a" … "z"
ident = letter { letter | decimalDigit | "_" }
fieldName = ident
```

As you can see, the `fieldName` is an `ident` and an `ident` must start with a `letter`.

https://github.com/timostamm/protobuf-ts/blob/55a7d5588afad4a98e57dc35789d97650d96da43/packages/test-fixtures/name-clash.proto#L4-L6

As shown in the `name-clash.proto` file above there is an example of a field name starting with an underscore. It doesn't seem like we should even have to test against this as I would expect `protoc` to throw a parsing error as soon as it encounters this non-conformant proto field name. But clearly that isn't the case. Instead what happens is that code gets generated for this proto file, but it doesn't provide the output that I would expect based on looking at https://github.com/timostamm/protobuf-ts/blob/55a7d5588afad4a98e57dc35789d97650d96da43/packages/plugin/src/interpreter.ts#L356-L363

I see the TS interface has a `Proto` field and the class's field info has no `localName` at all.

```ts
export interface ReservedFieldNames {
    /**
     * not allowed as object property, should be escaped
     *
     * @generated from protobuf field: string __proto__ = 1;
     */
    Proto: string;
    // ...etc.
}
// @generated message type with reflection information, may provide speed optimized methods
class ReservedFieldNames$Type extends MessageType$<ReservedFieldNames> {
    constructor() {
        super("spec.ReservedFieldNames", [
            { no: 1, name: "__proto__", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            // ...etc.
        ]);
    }
}
```

The reason this happens is because `FieldInfoGenerator.createTypescriptLocalName` calls `rt.lowerCamelCase` and `rt.lowerCamelCase('__proto__') === 'Proto'`. At the very minimum I think the logic here needs to be replaced https://github.com/timostamm/protobuf-ts/blob/55a7d5588afad4a98e57dc35789d97650d96da43/packages/plugin/src/interpreter.ts#L408-L412

What's the reason the logic isn't simply the following? Am I missing something?
```ts
// localName: The name of the field in the runtime.
let localName = this.createTypescriptNameForField(fieldDescriptor);
if (localName !== fieldDescriptor.name) {
    info.localName = localName;
}
```

**Comment by timostamm** [comment]
The published EBNF is not accurate, unfortunately. See [Joshua Humphries great work](https://github.com/jhump/protocompile/tree/master/grammar) on this.

We use protoc's lowerCamelCase algorithm to create our property names. The fact that it turns `__proto__` into `Proto` is certainly odd. It is also possible that our implementation doesn't match protoc completely, I have not tested it in depth.

The reason we don't always generate `localName` is that we can usually trivially infer `localName` from `lowerCamelCase(name)`, and shave off some code size in that case. If we changed the logic to your last example, names would stay the same, but we would generate more code.

**Comment by jcready** [comment]
Ah. Very interesting. I thought that was actually going to cause runtime bugs, but I forgot about the field normalization that happens in the MessageType constructor.
