### ISSUE TITLE
Keepalive

### ISSUE THREAD

**Issue by cipriantarta** [timostamm/protobuf-ts#305]
I have a server streaming rpc behind envoy and it basically runs forever, but envoy will drop the connection every 5 minutes if there are no messages sent over the network, which is sort of a good thing.

I have implemented the server side keepalive as described [here](https://github.com/grpc/grpc/blob/master/doc/keepalive.md#faq) and I want to add that into my client as well, but I can't find anything related to that in this repo.

Any guidance is appreciated.

**Comment by Bluskript** [comment]
if there is no keepalive implemented here already, I would recommend creating a streaming interceptor that would do whatever is necessary to maintain the keepalive. This is moreso an implementation detail, protobuf-ts doesn't expect keepalives to be an issue and relies on a Transport to deliver extended functionality. This might be a useful PR to `@protobuf-ts/grpc-transport` or maybe `@protobuf-ts/grpcweb-transport`

**Comment by timostamm** [comment]
For a generated `client_grpc1` client, the third constructor argument is a `grpc.ClientOptions` object:

https://github.com/timostamm/protobuf-ts/blob/44b0fe4b7fe202c4d8a51f785c60ce71ca717622/packages/example-node-grpc-client/client.ts#L6-L11

This object also takes `grpc.ChannelOptions`, including `grpc.keepalive_time_ms` and [other related settings](https://github.com/grpc/grpc-node/issues/154). That means you can pass arguments like this:

```diff
const client = new ExampleServiceClient( 
     "localhost:5000", 
     ChannelCredentials.createInsecure(), 
-     {},
+     {
+        "grpc.keepalive_time_ms": 1500
+     }, 
     {} 
 ); 
```

If you are using our generic clients with `@protobuf-ts/grpc-transport`, `grpc.ClientOptions` are passed to the transport constructor:

https://github.com/timostamm/protobuf-ts/blob/44b0fe4b7fe202c4d8a51f785c60ce71ca717622/packages/example-node-grpc-transport-client/client.ts#L7-L10

```diff
const transport = new GrpcTransport({
    host: "localhost:5000",
    channelCredentials: ChannelCredentials.createInsecure(),
+   clientOptions: {
+       "grpc.keepalive_time_ms": 1500,
+   }
});
```

If you notice any issues, please let me know.

**Comment by cipriantarta** [comment]
@timostamm thanks for looking into this, unfortunately I can't get this to work, envoy still kills my connection 5 minutes later.
This is the transport:
```
  const transport = new GrpcWebFetchTransport({
    baseUrl: grpcUrl,
    format: 'binary',
    meta: { Authorization: `Bearer ${idToken}` },
    clientOptions: {
      "grpc.keepalive_time_ms": 6000
    }
  })
```

**Comment by cipriantarta** [comment]
I looked into `GrpcWebFetchTransport` and indeed it doesn't have `clientOptions`, that's only for the `GrpcTransport` which I can't use in the browser.
