### ISSUE TITLE
Argument of type 'GrpcWebFetchTransport' is not assignable to parameter of type 'RpcTransport'

### ISSUE THREAD

**Issue by Janaka-Steph** [timostamm/protobuf-ts#311]
protobuf-ts: 2.6.0

```
export function selectProvisionClient(state: RootState): ProvisionServiceClient {
  return new ProvisionServiceClient(new GrpcWebFetchTransport({ baseUrl: selectGateEndpoint(state) }));
}
```

Gives error `Argument of type 'GrpcWebFetchTransport' is not assignable to parameter of type 'RpcTransport'`

NB: Forcing install of 2.5.0 doesn't work

yarn.lock
```
"@protobuf-ts/grpcweb-transport@2.5.0":
  version "2.5.0"
  resolved "https://registry.yarnpkg.com/@protobuf-ts/grpcweb-transport/-/grpcweb-transport-2.5.0.tgz#a571862f763aa59cd0d184d9f0f9fa6f0b0d920a"
  integrity sha512-8NRvhcwkKyLFrV9j6C3aYtlCLvRvlCgQ0957i63NUgvteZQCP0BGwbTVEQT2n43Wh3xO/Xhb+G1nFe04S3RYSA==
  dependencies:
    "@protobuf-ts/runtime" "^2.5.0"
    "@protobuf-ts/runtime-rpc" "^2.5.0"

"@protobuf-ts/runtime-rpc@2.5.0":
  version "2.5.0"
  resolved "https://registry.yarnpkg.com/@protobuf-ts/runtime-rpc/-/runtime-rpc-2.5.0.tgz#6c05c99c4b21dd7fbf1fe8398cec0515fc91f6a4"
  integrity sha512-zO5W1/66Ok68muvmjG0+ucTWTfzhCUurnqyspqcWGF9DDgGKSmrtR8V1MRV051UoTonOxm7NZZvM6VTbBv9DcA==
  dependencies:
    "@protobuf-ts/runtime" "^2.5.0"

"@protobuf-ts/runtime-rpc@^2.5.0":
  version "2.6.0"
  resolved "https://registry.yarnpkg.com/@protobuf-ts/runtime-rpc/-/runtime-rpc-2.6.0.tgz#66fbcf6d9b0ad0d5b892d86ef4e1fbd17516a26e"
  integrity sha512-PUAUUI4NJgg/3i0mfyxzrBsIs+V3/B+ybG2sDSf6mZhPYRZkUFBQqmnaFGx3UHOAU0JORqAIFC1dac6bUjaauw==
  dependencies:
    "@protobuf-ts/runtime" "^2.6.0"

"@protobuf-ts/runtime@2.5.0":
  version "2.5.0"
  resolved "https://registry.yarnpkg.com/@protobuf-ts/runtime/-/runtime-2.5.0.tgz#5264efa9b509cb1f6d9ccad7cbb3182430149cbe"
  integrity sha512-ClfuZQ3iPVABJ0CXLGI044eox1PtmrIbbXZaHYczdFJjaxxn8U7vnwb1dPBM9JZ2I6H1VLZu8A9Z5nRv7zydsg==

"@protobuf-ts/runtime@^2.5.0", "@protobuf-ts/runtime@^2.6.0":
  version "2.6.0"
  resolved "https://registry.yarnpkg.com/@protobuf-ts/runtime/-/runtime-2.6.0.tgz#d823470768383c0657cdc87a745c19af5ef63550"
  integrity sha512-ZXQxypattRL87U9Ki+unh2en+REp8m+VZDTCHHHt1gqTZpjbUn2zzELkSEmli+4WKWPEZRExIhzfAUz0xRskJQ==
```

**Comment by timostamm** [comment]
Hey Stéphane, this looks like a [limitation of yarn](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md):

> Basically, the problem with the current behaviour of yarn is that it is not possible to force the use of a particular version for a nested dependency.

Is there a reason you don't want to update to 2.6.0? Because it seems like this would be the easiest fix. Otherwise, check out the options in the link.

It's possible that peer dependencies will be best workaround for this situation, but I don't think it's wise to change anything before yarn berry has settled a bit.

**Comment by Janaka-Steph** [comment]
I don't mind using 2.6.0 but I have a TS error!! 
`Argument of type 'GrpcWebFetchTransport' is not assignable to parameter of type 'RpcTransport'`

**Comment by timostamm** [comment]
The TS error indicates that you are running two versions. What are the full error details? There should be more information.

**Comment by jacksonblankenship** [comment]
I'm getting the exact same error on version 2.7.0

**Comment by jacksonblankenship** [comment]
> I spy v2.8.1 and v2.7.0 in the yarn.lock. You can either update to latest with all, or ensure the lower version with "resolutions", see the [yarn docs](https://yarnpkg.com/configuration/manifest#resolutions).

Yep, turns out that was the issue! Thanks!
