### ISSUE TITLE
Does it support generating ES6 specification JS files and using them in grPC-Web

### ISSUE THREAD

**Issue by yl-yue** [timostamm/protobuf-ts#312]
Does it support generating ES6 specification JS files and using them in grPC-Web

**Comment by sessfeld** [comment]
It generates pure TypeScript, from there you can compile it however you like. I'm using [@protobuf-ts/grpcweb-transport](https://github.com/timostamm/protobuf-ts/blob/master/packages/grpcweb-transport) myself, and I'm more that happy with it.

**Comment by yl-yue** [comment]
Thank you for your reply.

Can I understand that I can develop in grPC-Web using pure TypeScript and therefore there is no JS file ES6 import problem because there are no (or no need for) JS files

**Comment by timostamm** [comment]
You cannot use protobuf-ts with [grpc-web](https://www.npmjs.com/package/grpc-web) and [protoc-gen-grpc-web](https://www.npmjs.com/package/protoc-gen-grpc-web). Both are hardwired for [google-protobuf](https://www.npmjs.com/package/google-protobuf) and `protoc --js_out`.

But you can use protobuf-ts as a replacement. The transport Sebastian mentioned implements gRPC-web.

And protobuf-ts can generate TypeScript, or JavaScript with ES6 imports and exports, or JavaScript with CommonJS. `protoc --js_out` can only generate CommonJS. If possible at all, I'd recommend ES6 over CommonJS.

**Comment by lotus-x** [comment]
Hi @yl-yue,

Is there any concerns to add `.js` extension to the imports?

**Comment by timostamm** [comment]
It would be pretty great if we could do that - enabled with an option - and make it default some time later. See https://github.com/timostamm/protobuf-ts/issues/182

**Comment by lotus-x** [comment]
I see, it's already in progress right.

Thanks for your hard work ❤️
