### ISSUE TITLE
Nested messages become optional

### ISSUE THREAD

**Issue by sebastiansandqvist** [timostamm/protobuf-ts#313]
In this example neither `toUser` nor `fromUser` is `optional`, yet in the generated ts output we see `toUser?:` and `fromUser?:`. This appears to only happen for non-array nested messages.

```ts
/**
 * @generated from protobuf message Ledger.Row
 */
export interface Ledger_Row {
    /**
     * @generated from protobuf field: Ledger.User to_user = 1;
     */
    toUser?: Ledger_User;
    /**
     * @generated from protobuf field: Ledger.User from_user = 2;
     */
    fromUser?: Ledger_User;
    /**
     * @generated from protobuf field: int32 amount = 3;
     */
    amount: number;
    /**
     * @generated from protobuf field: string description = 4;
     */
    description: string;
}

```

```protobuf
message Ledger {
  message User {
    string user_id = 1;
    string username = 2;
  }
  message Row {
    Ledger.User to_user = 1;
    Ledger.User from_user = 2;
    int32 amount = 3;
    string description = 4;
  }
}
```

**Comment by sessfeld** [comment]
Is that proto3? If I'm not mistaken, message fields in proto3 are always optional.

**Comment by sebastiansandqvist** [comment]
> Is that proto3? If I'm not mistaken, message fields in proto3 are always optional.

It is proto3. Does that mean that the following two `message`s are equivalent?

```protobuf
message Row {
    Ledger.User to_user = 1;
}

message Row {
    optional Ledger.User to_user = 1;
}
```

**Comment by timostamm** [comment]
@sebastiansandqvist, those two messages are indeed equivalent. I'm not sure why this ambiguity in the syntax is permitted. Maybe this wasn't thought through when proto3 optionals were added.

**Comment by sebastiansandqvist** [comment]
Good to know! In that case, the types are working as they should. Thank you!
