### ISSUE TITLE
Generate code compatible with `noUncheckedIndexAccess` flag

### ISSUE THREAD

**Issue by wagenet** [timostamm/protobuf-ts#314]
The current code does not compile if this flag is set to true in tsconfig.json's compilerOptions.

**Comment by timostamm** [comment]
It's not feasible to generate code that passes typechecks in all compiler configurations across TypeScript versions. 

Please use the [ts_nocheck option](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#the-protoc-plugin), it will become the default soon. If it does not work for you, please re-open.

CI of this project still typechecks the generated code and also runs parts of it, in case you wonder if ts_nocheck is a bad idea :)

Related: If you are using eslint, I recommend to set `eslint_disable` as well.

**Comment by wagenet** [comment]
Ah, thanks! I missed that flag.
