### ISSUE TITLE
Error using generated clients in Remix

### ISSUE THREAD

**Issue by srs** [timostamm/protobuf-ts#315]
I am trying to use the generated clients in Remix (remix.run) and it fails. Remix gives me `TypeError: XXX is not a constructor` when creating a new client.

Found out why and it's because Remix (and other SSR frameworks) uses different loaders for `*.client.ts` and `*.client.js` files. When I rename this to something else, for example `*_client.ts` then it works fine.

My proposal is to add an option to the generation so it's possible to change the suffix for generated files - at least for client and server stubs.

What do you think?

**Comment by timostamm** [comment]
Could you give a bit more detail where this error is reported? Is it in generated code or in the runtime library (@protobuf-ts/runtime). 

What code do you generate... just TypeScript files, or do you generate JavaScript + declaration files (`.js`, `.d.ts`)?

**Comment by matdehaast** [comment]
@timostamm we ran into this. It is in neither. It has to do with the fact that any `.client` file is not available to the server code as a convention.

We just need a way to choose the postfix for `client` in the options. We are just running a script on the generated files after to rename it for now as a stop gap.

**Comment by jcready** [comment]
>It has to do with the fact that any `.client` file is not available to the server code as a convention.

Just playing devil's advocate here, but why not file a bug with Remix to make that convention configurable? It looks like another option available to you would be to configure `protoc` to output the generated files to your `node_modules` directory (or apparently any directory aside from `app`) as [Remix only applies that behavior to files inside the `app` directory](https://github.com/remix-run/remix/blob/5b8a0ce0aa0201aa2402fc41405ffbe89605963b/packages/remix-dev/compiler/plugins/emptyModulesPlugin.ts#L20-L23).

**Comment by cairin** [comment]
> why not file a bug with Remix to make that convention configurable?

We could, but it's unlikely they would do that. The complexity of adjusting their build system to accomodate the change >> changes required in this package.

> output the generated files to your node_modules directory (or apparently any directory aside from app)

Putting generated files inside node modules isn't always plausible. If you're using yarn 3 with pnp, you simply can't. Neither of these methods work without fiddling with the remix build system, which is not ideal.

**Comment by srs** [comment]
> why not file a bug with Remix to make that convention configurable?

It seems that other frameworks are considering (or actually implemented) the `client` and `server` file-suffix. So I think this would be not very feasible to change.

Today I am using a script for renaming `.client.ts` to `_client.ts` which work's fine, but would be better to have it configured in the generator.

**Comment by timostamm** [comment]
Looks to me like remix owns the `appDirectory`. That's fair - there have already been numerous frameworks applying behaviour based on file names and file locations and it's a valid approach. Usually you author the files in the directory yourself, so you just name the files accordingly.

However, a code generator is a bit similar - it writes files following a specific logic, and also owns the directory. If you let two different pieces of software own the same directory, yeah, it can cause conflicts.

The simple solution here would be to generate into a directory `gen` as a sibling to `app`. I'd check the generated files in (you can use [linguist-generated](https://github.com/github/linguist/blob/master/docs/overrides.md) so they don't blow up PRs) and actually clean the directory and re-generate in CI to check that they are up-to-date. That approach works out pretty nicely. You could even set a [path in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths), so you can reference generated code with `import from "@gen/foo/bar"`. That also works with [npm or yarn workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces).

This seems a bit more sensible than adding a plugin option. If the next framework adds another conflicting convention, we'd be at the same place as before.

Closing this, but if the solution above doesn't work, let me know.

**Comment by cairin** [comment]
@timostamm Thanks for this.

Unfortunately, your proposed solution doesn't quite work.

To be verbose: In Remix you can specify `.client.ts` or `.server.ts` file extensions. Remix will prune `.client.ts` code from the server bundle, and vice versa. This ensures that those files will only be loaded on the client/server respectively. Remix does some smart code pruning (besides this mechanism), but this mechanism allows the user to set hard boundaries between the client and server code bundles. This is useful for running code that would not work in the other environment, or if you want to prevent certain code ever getting to the other environment.

Now, it seems that when you explicitely use the `.server.ts` file extension, remix will just prune any imports of any module that ends in `.client` regardless of where it comes from (inside/outside the `appDirectory`). So you end up with code that isn't defined, hence the error above.

**Comment by timostamm** [comment]
I'm afraid I need a bit more detailed information to follow your argument. 

If you look at 



> To be verbose: In Remix you can specify .client.ts or .server.ts file extensions. Remix will prune .client.ts code from the server bundle, and vice versa.

Yes. For the server build, remix adds an esbuild plugin that prunes

**Comment by yehudamakarov** [comment]
still can't use generated typescript clients in remix and its a bummer, happy I finally found this issue.

do I have to throw out my architecture now or there is some way forward? i can't tell from the issue's comments. @timostamm did you want someone to take forward debugging the remix compiler against your library's outputs? 

As of now the clients simply cannot be used in a remix app and that's a downright shame. (unless I missed a solution somewhere?)

any help appreciated - thanks dearly

**Comment by yehudamakarov** [comment]
> > It has to do with the fact that any `.client` file is not available to the server code as a convention.
> 
> Just playing devil's advocate here, but why not file a bug with Remix to make that convention configurable? It looks like another option available to you would be to configure `protoc` to output the generated files to your `node_modules` directory (or apparently any directory aside from `app`) as [Remix only applies that behavior to files inside the `app` directory](https://github.com/remix-run/remix/blob/5b8a0ce0aa0201aa2402fc41405ffbe89605963b/packages/remix-dev/compiler/plugins/emptyModulesPlugin.ts#L20-L23).

since I am using this with `buf` my generated files **are** in `node_modules` and I have the same problem - how does that make sense along with your comment @jcready

**Comment by yehudamakarov** [comment]
in case this helps anyone in the future, this is something I'm working with at the moment: `"postinstall": "find ./node_modules -type f -path '*/@buf/*' -regex '.*<my service>.*client.*' -exec sh -c 'mv \"$1\" \"$(echo \"$1\" | sed -E \"s/\\.client\\.(d\\.ts|js)$/._client.\\1/\")\" ' sh {} ';' && remix setup node",` 

beware of `jobservice` above I'm filtering only `<my service>` because I don't want to change other proto files that have `.client` in their name
