### ISSUE TITLE
Parsing protos in runtime

### ISSUE THREAD

**Issue by lotus-x** [timostamm/protobuf-ts#317]
Hi,

I want to serdes proto messages in runtime with kafka schema registry.

Does the library support for parsing a proto string in runtime, get reflection details and encode/decode messages on the fly?

**Comment by timostamm** [comment]
Hey, this library does not implement a parser for proto - so this is not possible from proto files. Proto parsing is unfortunately not trivial, there are many edge cases that are only specified by the implementation `protoc`.

If you have file descriptors (protoc can output them) you can create protobuf-ts types at runtime. This requires quite a bit of translation from descriptors to our own simplified metadata. [interpreter.ts](https://github.com/timostamm/protobuf-ts/blob/master/packages/plugin/src/interpreter.ts) does exactly that. It is not a happy path though, this isn't part of the public API.
