### ISSUE TITLE
Can't use generated models as type option in Vue props

### ISSUE THREAD

**Issue by someone1** [timostamm/protobuf-ts#33]
I feel like this is probably due to my lack of knowledge of TypeScript (and/or this package), but I can't figure out how to satisfy the following with the generated types from this package:

```ts
declare type PropConstructor<T> = {
    new (...args: any[]): T & object;
} | {
    (): T;
} | {
    new (...args: string[]): Function;
};
```

The closest I got to satisfying the compiler is:

```
import { ReportOption } from '@company/api-client';
//  ...
 props: {
    value: {
      required: true,
      type: () => ReportOption.create(),
    },
  },
```

But i'm greeted with the following error at runtime:
```
Invalid prop: type check failed for prop "value". Expected Type, got Object
```

I understand from the docs that the exported "model" is actually an instance implementing the `IMessageType` interface, but I'm lost on how to get this working.

**Comment by timostamm** [comment]
It's been some time since I used vue. To be honest, TypeScript appears to be an afterthought...

Use the syntax described here: https://vuejs.org/v2/guide/typescript.html#Annotating-Props

Instead of "ComplexMessage", use your "ReportOption". ReportOption is a simple interface just like ComplexMessage. 

```typescript
import { ReportOption } from '@company/api-client';
// ...
props: {
  value: {
    required: true,
    type: Object as PropType<ReportOption>,
  }
}
```

I am not sure why they recommend to cast as PropType. I don't see any benefit.

I´d take a look at Class-Style components. Seem to be a better match for TypeScript: 
https://vuejs.org/v2/guide/typescript.html#Class-Style-Vue-Components

**Comment by someone1** [comment]
Thanks for the tip - still doesn't seem to be working though. I opened an [issue](https://github.com/vuejs/composition-api/issues/601) on the [@vue/composition-api](https://github.com/vuejs/composition-api/) project for this. I thought my understanding of the types generated from this package may have been lacking, I haven't run into this issue with other types I've built components around, but even trying the `ComplexMessage` example you linked to seems to be failing.

I've built multiple apps using the Class Style in Vue, but I'm trying to build my next app with the new Composition API. There are limits/quirks of the Class Style that I hope to be resolved with [Vue 3 being written in TypeScript](https://v3.vuejs.org/guide/typescript-support.html#official-declaration-in-npm-packages) - no longer making it an afterthought.

The compiler error:
```
No overload matches this call.
  Overload 1 of 3, '(options: ComponentOptionsWithoutProps<unknown, unknown, Data, {}, {}>): VueProxy<unknown, unknown, Data, {}, {}>', gave the following error.
    Type '{ value: { required: true; type: PropType<ReportOption>; }; }' is not assignable to type 'undefined'.
  Overload 2 of 3, '(options: ComponentOptionsWithArrayProps<string, Data, Data, {}, {}, Readonly<{ [x: string]: any; }>>): VueProxy<Readonly<{ [x: string]: any; }>, Data, Data, {}, {}>', gave the following error.
    Type '{ value: { required: true; type: PropType<ReportOption>; }; }' is not assignable to type 'string[]'.
      Object literal may only specify known properties, but 'value' does not exist in type 'string[]'. Did you mean to write 'values'?
  Overload 3 of 3, '(options: ComponentOptionsWithProps<ComponentPropsOptions<Data>, Data, Data, {}, {}, ({ [x: number]: string; } & { length?: number | undefined; toString?: string | undefined; ... 29 more ...; flat?: unknown[] | undefined; }) | ({} & { ...; })>): VueProxy<...>', gave the following error.
    Type '{ value: { required: true; type: PropType<ReportOption>; }; }' is not assignable to type 'string[] | ComponentObjectPropsOptions<Data> | undefined'.
      Types of property 'value' are incompatible.
        Type '{ required: true; type: PropType<ReportOption>; }' is not assignable to type '(new (...args: string[]) => Function) | PropOptions<unknown, unknown> | (new (...args: any[]) => object) | (() => unknown) | PropConstructor<unknown>[] | null | undefined'.
          Types of property 'type' are incompatible.
            Type 'PropType<ReportOption>' is not assignable to type 'true | (new (...args: string[]) => Function) | (new (...args: any[]) => object) | (() => unknown) | PropConstructor<unknown>[] | null | undefined'.
              Type 'new (...args: never[]) => ReportOption & object' is not assignable to type 'true | (new (...args: string[]) => Function) | (new (...args: any[]) => object) | (() => unknown) | PropConstructor<unknown>[] | null | undefined'.
                Type 'new (...args: never[]) => ReportOption & object' is not assignable to type 'new (...args: string[]) => Function'.
                  Types of parameters 'args' and 'args' are incompatible.
                    Type 'string' is not assignable to type 'never'.
```
