### ISSUE TITLE
eslint error on protobuf empty

### ISSUE THREAD

**Issue by tetra12** [timostamm/protobuf-ts#353]
When I generate an empty message in proto3 like this `message Empty {}`, I'm getting a compile error from `eslint` inside the generated file: `An empty interface is equivalent to {}`

This can be fixed by adding this :
```bash
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Empty {}
```
I would not like to make a hand :hand: change of generated files all the time. Is it possible to fix this?

Thanks!

**Comment by jcready** [comment]
You can add `eslint_disable` to the `protoc` plugin options `--ts_opt eslint_disable`. [See manual](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#the-protoc-plugin).

```
npx protoc \
  --ts_out src/generated/ \
  --ts_opt eslint_disable \
  --proto_path protos \
  protos/my.proto 
```

**Comment by tetra12** [comment]
@jcready Thanks ! That solved my issue
