### ISSUE TITLE
.toJson should return JsonObject instead of JsonValue?

### ISSUE THREAD

**Issue by mentos1386** [timostamm/protobuf-ts#355]
How come `toJson`[1] has return type of `JsonValue`[2] instead of `JsonObject`[3]. Is there ever an expected output that is not a `JsonObject`?

This seams to be inherited from `ReflectionJsonWriter.write`[4], but there doesn't seem to be possible to return other than `JsonObject`.

[1]
https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/runtime/src/message-type.ts#L178-L183

[2]
https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/runtime/src/json-typings.ts#L1-L10

[3]
https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/runtime/src/json-typings.ts#L13-L16

[4]
https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/runtime/src/reflection-json-writer.ts#L31

**Comment by timostamm** [comment]
A regular message serializes to a JSON object, that is correct.
But the [well-known types](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#well-known-types) don't. For example, a google.protobuf.TimeStamp serializes to a string.

**Comment by timostamm** [comment]
Closing, but if you think this is an issue, please feel free to re-open. It would be helpful to know about your use case.
