### ISSUE TITLE
Relax constraints on runtime-angular to include Angular 14

### ISSUE THREAD

**Issue by ColinLaws** [timostamm/protobuf-ts#357]
Angular 14 is available, however the runtime-angular package is still constrained to a maximum of Angular 13. I recommend relaxing the constraints to allow for 14, permitting that there are no conflicts with moving to newer versions of TypeScript (if need be).
https://github.com/timostamm/protobuf-ts/blob/02c82bdc66e1cf2bea199906c580e9d75ff93bcf/packages/runtime-angular/package.json#L35-L36

**Comment by ColinLaws** [comment]
Submitted PR #358

**Comment by timostamm** [comment]
Merged - thanks for the PR!
