### ISSUE TITLE
Metadata empty on RPCError

### ISSUE THREAD

**Issue by codesuki** [timostamm/protobuf-ts#370]
Hi there! Great job with the library!

I am playing around and wanted to test a bit more complex gRPC errors. 
```	st := status.New(codes.Aborted, "aborted")
	st, err := st.WithDetails(&somepb.Something{Something: "some details"})
	return nil, st.Err()
```
Now I was expecting to find the `Something` message attached in the metadata or similar field on the RpcError. But it's always empty. What I get is something like this ```RpcError{code: "ABORTED", name: "RpcError", message: "aborted", metadata: {}}```

There might be other layers affecting the outcome of this like some Envoy setting or whatnot. Does anyone successfully use this feature or could try in their setup if it works?

**Comment by timostamm** [comment]
Hey @codesuki, apologies for the super late response 🙈

The error details are encoded in a header or trailer field `grpc-status-details-bin`. It is a [google.rpc.Status](https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto) message, base64 encoded.

This library does not attempt to parse the details, but you should be able to do so manually.

**Comment by timostamm** [comment]
Oh, I see that metadata is empty. If you are using gRPC-web, make sure the headers are CORS allowlisted. If the header still does not show up, this might be a bug in this library, and I'd be interested in a confirmation.

**Comment by codesuki** [comment]
Yep, that was it! Totally forgot about the CORS settings. Thanks!
