### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by Ludea** [timostamm/protobuf-ts#377]
Hi, I try to call a rpc function from a browser.
 I get 
```
Access to fetch at http://127.0.0.1:3000/rpc.Service.func from origin http://localhost:5173 has been blocked by CORS policy: response to preflight request doesn't pass access control check: No Access-Control-Allow-Origin header is present on the requested resource. If an opaque response serve your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disable
``` 
I use grpc-web transport and server is https://github.com/hyperium/tonic/blob/master/examples/src/grpc-web/server.rs. 
Issue is from server side or client side ? Can protobuf-ts had support for this CORS

**Comment by timostamm** [comment]
Hey Ludea, there is nothing that can be done client-side, this needs to be set up on the server.

For a simple intro to CORS, see https://httptoolkit.com/will-it-cors/

For more details, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
