### ISSUE TITLE
Stream response with grpc-web transport 

### ISSUE THREAD

**Issue by Ludea** [timostamm/protobuf-ts#381]
Hi,
I try to retrieve stream data
```
const status = async(client: IRepoClient, path: string) => {  
  const call = client.status({
      path: path
    });
      for await (let response of call.responses) {
       console.log("foo "); 
        console.log("got : " + response);
  } 
}
```
There is no output from browser console.
I check with Bloomrpc, the server send the stream as expected.
If I print `call.response` before loop, I get strange json output.

I miss something ?

**Comment by timostamm** [comment]
Looks correct to me. Are you sure you are hitting a gRCP-**web** server, not plain gRPC?

Perhaps this example helps to identify a missing piece: https://github.com/timostamm/protobuf-ts/tree/master/packages/example-node-grpcweb-transport-client

**Comment by Ludea** [comment]
I follow https://github.com/timostamm/protobuf-ts/tree/master/packages/example-browser-grpcweb-transport-client because I use it throuhgh browser.

I enable http1 and grpc-web from server : https://github.com/timostamm/protobuf-ts/tree/master/packages/example-browser-grpcweb-transport-client (it's a rust implementation based on tonic, https://github.com/hyperium/tonic

and the client : https://github.com/Ludea/lucle/blob/main/web/src/views/Speedupdate.tsx#L45

Note: unary call work as expected

the message I get when I print call.response `{"_lis":{"nxt":[],"msg":[],"err":[],"cmp":[]},"_closed":true}`

**Comment by timostamm** [comment]
This could be a regression in our grpcweb-transport, a bug in ludea, a misunderstanding between the two protocol implementations, or a simple misconfiguration. 

To isolate the problem, I'm afraid you have to try hitting the server with other gRCP-web implementations. It's really unfortunate that there is [no formal gRPC-web specification](https://github.com/grpc/grpc/issues/30565).

**Comment by Ludea** [comment]
will try with connect-web

**Comment by Ludea** [comment]
Works as expected with
```const call = client.status({ path });
for await (const response of call.responses) {
    console.log("got a message", response);
}
const {status, trailers} = await call;
```
