### ISSUE TITLE
String enum in nested fields

### ISSUE THREAD

**Issue by tomas-carv-com** [timostamm/protobuf-ts#382]
I have proto which contains map with other proto:

```
message Meeting{
    enum MeetingState {
        Uploading = 0;
        Processing = 1;
        Error = 2;
        Done = 3;
    }
MeetingState state = 3;
`map<string, Participant> participants = 5;`
}
```

and participant has

```
message Participant{
enum ParticipantRole {
        Viewer = 0;
        Editor = 1;
        Owner = 2;
    }
ParticipantRole role = 3;
}
```

However when called:
 `const tmp = Meeting.toJson(this, { enumAsInteger: false, emitDefaultValues: false, });`

**### role == 0 not 'Viewer'**

Obviously setting work fine for root level, so meetingState is correctly set to 'Uploading'

**Comment by timostamm** [comment]
I would expect the following JSON for the following message:

```ts
const m = Meeting.create({
  state: MeetingState.Done
})

Meeting.toJsonString() // '{"state": "Done"}'
```

Can you provide some context? It's not clear to me whether you are reporting a bug or requesting a feature.

**Comment by tomas-carv-com** [comment]
@timostamm that is correct asumption state is 'Done' but nested map should be
```
{
"state":"Done",
  "participants":{
    "documentId::{
      "role":"Viewer"
    }
  }
}
```

However it is:
```
{
"state":"Done",
  "participants":{
    "documentId::{
      "role":0
    }
  }
}
```

**Comment by timostamm** [comment]
Thank you for the bug report, @tomas-carv-com. Unfortunately, the proto source you gave doesn't compile, and you didn't provide a runnable piece of code using it. That makes it difficult to reproduce what you are actually doing. 

I suppose you have a map field, and map value is a message with an enum field:

```proto
// m.proto
syntax="proto3";
enum E {
  E_UNSPECIFIED=0;
  E_A=1;
  E_B=2;
}
message M {
  E e = 1;
  map<string,M> map = 2;
}
```

And you somehow create an instance of it:

```ts
// index.ts
import {M, E} from "./m";

const m = M.create({
  map: {
    "key": {
      e: E.E_A,
     }
  }
})

console.log(
  M.toJsonString(m)
)
```

I'm still seeing the expected output here:

```bash
$ npx tsx index.ts         
{"map":{"key":{"e":"E_A"}}}
```

Closing this. If you are certain you have found a bug, please reopen! But please follow up with a reproducible example.

**Comment by tomas-carv-com** [comment]
I am not sure what are you talking about. I gave the proto files above, those are just partial messages exactly talking only about enums.

meeting.proto file can be like here:

```
syntax = "proto3";
import "participant.proto";
message Meeting{
    enum MeetingState {
        Uploading = 0;
        Processing = 1;
        Error = 2;
        Done = 3;
    }
    MeetingState state = 1;
    map<string, Participant> participants = 2;
    }
```

with participant.proto
```
syntax = "proto3";

message Participant{
    enum ParticipantRole {
        Viewer = 0;
        Editor = 1;
        Owner = 2;
    }
     string participantId = 1;
    ParticipantRole role = 2;
    optional string name = 3;
    }
```

And I used your example:

```
import { Meeting, Meeting_MeetingState } from "./proto/meeting_pb"
import { Participant_ParticipantRole } from "./proto/participant_pb"


const m = Meeting.create({
    state: Meeting_MeetingState.Done,
    participants: {
        "1": { name: "John", role: Participant_ParticipantRole.Viewer, participantId: "1" },
    }
})

console.log(
    Meeting.toJsonString(m)
)
```

which resulted in
`{"state":"Done","participants":{"1":{"participantId":"1","name":"John"}}}`

This one even completely omitting nested role for some reason.

**Comment by timostamm** [comment]
I'm asking for a minimal, reproducible example as [described here](https://stackoverflow.com/help/minimal-reproducible-example). Will make it much easier to identify a problem :)

> which resulted in
> `{"state":"Done","participants":{"1":{"participantId":"1","name":"John"}}}`
> 
> This one even completely omitting nested role for some reason.

This is not very intuitive when starting with protobuf, but expected. Enum zero values are the default, you can learn more about them [here](https://developers.google.com/protocol-buffers/docs/proto3#enum).

**Comment by tomas-carv-com** [comment]
Ah yeah make sense. Ok let me run whole suite of my tests, and will get back to you tomorrow if I am still facing issues. THX for quick reply and understanding
