### ISSUE TITLE
Compiled types have a prefix when using the same file name twice

### ISSUE THREAD

**Issue by mcblum** [timostamm/protobuf-ts#383]
I'm building my TS types and the protos structure looks like this:

```
apione
apitwo
docs
```
Both the `apione` and the `apitwo` folders have an `enums.proto` file in it.

When `apione/resource.ts` imports from `../apitwo/enums.ts` there's this stage thing that happens where to every enum it adds `apitwo`. So in the TS I see:

`dependency_1.apitwoNameOfEnum` whereas it should be `NameOfEnum`.

Because of this, Typescript won't compile. My command options are `--ts_opt=ts_nocheck --ts_opt=eslint_disable --ts_opt=no_namespace --ts_opt=explicit_override`. I cannot seem to figure out how to fix this. Please let me know if you have any ideas!

**Comment by mcblum** [comment]
Quick update -- it looks like this is happening because of:

```
message Entity {
   apitwo.EntityType = 3
}
```

Still haven't been able to fix it, but I believe that's the issue.

**Comment by timostamm** [comment]
Matt, you mention that TypeScript won't compile. This sure sounds like a bug, but it's very unclear to me where we would generate something like `dependency_1.apitwoNameOfEnum`. We throw a really large amount of proto files at the plugin in the tests, and I've never seen this.

Please take a look at the top of the generated files. Does it say the following?

```
// @generated by protobuf-ts ...
```

Our plugin does not have the options `no_namespace` or `explicit_override`, so I suspect you are generating code with a different plugin. 

If that is not the case, please re-open the issue. A minimal reproducible example would be greatly appreciated.
