### ISSUE TITLE
`reflectionMergePartial()` will overwrite target oneof field even if source has none set

### ISSUE THREAD

**Issue by jcready** [timostamm/protobuf-ts#386]
https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/runtime/src/reflection-merge-partial.ts#L39-L49

```proto
message Foo {
  oneof bar {
    optional int32 baz = 1;
    optional int32 qux = 2;
  }
}
```

```ts
const src = Foo.create();
const dst = Foo.fromJson({ baz: 1 });
Foo.mergePartial(dst, src);
Foo.toJson(dst); // {}
```

I don't know for sure if this behavior is correct or incorrect, but it _feels_ incorrect to me considering how `reflectionMergePartial()` treats other fields where the source field is unset: https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/runtime/src/reflection-merge-partial.ts#L51-L55

I would **not** expect an _unset_ oneof field in the source to overwrite/unset a _set_ oneof field in the target. I believe the fix would be to update line 40 to:

```diff
- if (group == undefined) { // the user is free to omit
+ if (group?.oneofKind == undefined) { // the user is free to omit
```

**Comment by timostamm** [comment]
> I would not expect an unset oneof field in the source to overwrite/unset a set oneof field in the target.

I agree with that. Good shout.
