### ISSUE TITLE
How to use google/protobuf/any.proto 

### ISSUE THREAD

**Issue by SyedAsimAliSE** [timostamm/protobuf-ts#39]
```proto

// I am using Any type in one of my proto file 

import "google/protobuf/any.proto";
```

But when i am running the generator it is generating the import like :

```typescript
import { Any } from "./google\\protobuf\\any";
```

![image](https://user-images.githubusercontent.com/44644354/100389562-819c8400-304f-11eb-973b-87d69e9d71df.png)

**Comment by timostamm** [comment]
That looks interesting :) 

Do you happen to be on Windows?

**Comment by SyedAsimAliSE** [comment]
yep i am using windows 10

**Comment by timostamm** [comment]
Ok. I'm pretty sure that this "importPath" has windows path separators (\\) that have to be swapped.

https://github.com/timostamm/protobuf-ts/blob/7d0855f6f25e017f3f644679eacc734e33bcca32/packages/plugin-framework/src/typescript-import-manager.ts#L79-L82

But I have to setup a test env to confirm and fix. You'll have to wait a few days...

In the meantime, I can think of two workarounds:
1. run protoc in the linux subsystem (WSL)
2. replace paths in generated code with search and replace

**Comment by SyedAsimAliSE** [comment]
it seems it need path normalization , i already tried to replace paths, but it says module not found . 
```typescript 
import { Any } from "./google/protobuf/any";
```
![image](https://user-images.githubusercontent.com/44644354/100392981-26bc5a00-305a-11eb-9359-2dd67cb27eb8.png)

Managed to compile it with :
```typescript 
import { Any } from "google-protobuf/google/protobuf/any_pb.js";
```

but don't know if it works or not because i am unable to go past this :

i am trying to migrate from ```grpc-js``` to ```protobuf-ts```  in my NestJS project, using ```nodejs 14.15.1``` with ```tsconfigs ``` set to ES2020.

after reading the documentation installed ```Twirp transport``` 

and added the following call to the server.

```typescript
                const transport = new TwirpFetchTransport({
			baseUrl: "0.0.0.0:50052"
		});

		const client = new ProcessTypeWritesServiceClient(transport);

		const payload:CreateProcessTypeInput_GRPC = {
			processTypeStatus:input.processTypeStatus
		}

		const {response} = await client.createProcessTypeGRPC(payload);
		console.log("Response! " + response)
```

but getting :

```bash
TypeError: globalThis.Headers is not a constructor at TwirpFetchTransport.unary 
```

thanks

**Comment by timostamm** [comment]
> ```ts
> import { Any } from "./google/protobuf/any";
> ```

That should work. I guess the file is not there? 

Use protoc argument '--ts_opt generate_dependencies':

> - "generate_dependencies"  
>  By default, only the PROTO_FILES passed as input to protoc are generated, 
>  not the files they import. Set this option to generate code for dependencies 
>  too.

Are you running the twirp transport in nodejs? 

> This transport requires the fetch API. `globalThis.fetch`, `globalThis.Headers` and `globalThis.AbortController` are expected. The transport is tested with the polyfill packages [node-fetch](https://github.com/node-fetch/node-fetch) and [`abort-controller`](https://github.com/mysticatea/abort-controller).

**Comment by SyedAsimAliSE** [comment]
You are right i missed the flag ```--ts_opt generate_dependencies``` i got the any file.

![image](https://user-images.githubusercontent.com/44644354/100394592-81a48000-305f-11eb-9e08-6a333f07c485.png)

yes i am running it in nodejs, also installed ```node-fetch and abort-controller``` both of them but i have no idea what to do next with them :D because it still says ```TypeError: globalThis.Headers is not a constructor at TwirpFetchTransport.unary ```

**Comment by timostamm** [comment]
Have a look here: 

https://github.com/timostamm/protobuf-ts/blob/7d0855f6f25e017f3f644679eacc734e33bcca32/packages/twirp-transport/clientcompat/client.ts#L12-L16

And here:

https://github.com/timostamm/protobuf-ts/blob/7d0855f6f25e017f3f644679eacc734e33bcca32/packages/test-generated/spec/generated-client-style-call.spec.ts#L3-L6

**Comment by SyedAsimAliSE** [comment]
i tried everything but it seems to fail on me every time. if i don't set ```Headers``` then it is always giving :

```bash 
TypeError: globalThis.Headers is not a constructor
```
if uncomment it ,getting the following type errors. did google for it allot but i guess i am the only one getting these :(

![image](https://user-images.githubusercontent.com/44644354/100396509-1bbbf680-3067-11eb-9529-aa22d117a879.png)

```bash
error TS2322: Type 'typeof Headers' is not assignable to type '{ new (init?: HeadersInit): Headers; prototype: Headers; }'.
  The types of 'prototype.forEach' are incompatible between these types.
    Type '(callback: (value: string, name: string) => void) => void' is not assignable to type '(callbackfn: (value: string, key: string, parent: Headers) => void, thisArg?: any) => void'.
      Types of parameters 'callback' and 'callbackfn' are incompatible.

37 globalThis.Headers = Headers;
   ~~~~~~~~~~~~~~~~~~

```

**Comment by timostamm** [comment]
The code snippets in the comments above are part of the CI workflow.  
They run on every single commit to this repository, in node js.  
They also run every single time I make a release. 

Take a step back and get Headers working as expected, see examples here: https://developer.mozilla.org/en-US/docs/Web/API/Headers

The fetch API is nice and node-fetch is an excellent implementation.  
Try making some simple requests, then add some custom headers.

Once you have that working, the TypeError is either gone - or you should be confident enough to just do `globalThis.Headers = Headers as unknown as any;`  This will suppress the TypeError. But if you have some import error or broken node-fetch version, it will not help you at all. So get fetch and Headers running first.

**Comment by SyedAsimAliSE** [comment]
found out that the problem is not with the node-fetch lib.

The ```globalThis.Headers = Headers;``` is taking me to the ```nestjs Header const declaration```  

```typescript
export declare const Headers: (property?: string) => ParameterDecorator;
```

and the error is always taking me to this 

```typescript
globalThis.fetch(url, {
            --
            headers: createTwirpRequestHeader(new globalThis.Headers(), !!opt.sendJson, opt.meta),
            --
            --
        })
```

now need to find out how do i switch this global for the protobuf-ts.

**Comment by SyedAsimAliSE** [comment]
Alright the problem with ```globalThis.Headers = Headers;``` is really not a problem but Intellij IDE isn't picking up the TS Typings, the project is working in VSCode perfectly fine.

**Comment by timostamm** [comment]
I'm using jetbrains IDEs as well. Some times the TypeScript service shows invalid errors. Helps to restart it in this case. 

![Bildschirmfoto 2020-11-27 um 21 50 40](https://user-images.githubusercontent.com/4289451/100483882-af8ad280-30fa-11eb-83f4-61b140a5a4bb.png)

But your issue might have been something else. Glad you solved it.

**Comment by timostamm** [comment]
> But when i am running the generator it is generating the import like :
> 
> ```ts
> import { Any } from "./google\\protobuf\\any";
> ```

Fixed in v1.0.11

**Comment by SyedAsimAliSE** [comment]
Thank you for taking your time :)

For anyone encountering the ```globalThis.Headers = Headers;``` problem in Intellij IDE, can solve it like this:

![unknown](https://user-images.githubusercontent.com/44644354/100515323-182a8b80-319d-11eb-8ad8-f816a483a50c.png)

**Comment by hamming** [comment]
> ```protobuf
> // I am using Any type in one of my proto file 
> 
> import "google/protobuf/any.proto";
> ```
> 
> But when i am running the generator it is generating the import like :
> 
> ```ts
> import { Any } from "./google\\protobuf\\any";
> ```
> 
> ![image](https://user-images.githubusercontent.com/44644354/100389562-819c8400-304f-11eb-973b-87d69e9d71df.png)

1. npm install node-fetch
2. npm install abort-controller

3. and --ts_opt generate_dependencies in your cmd
