### ISSUE TITLE
FieldMask JSON read/write (snake_case <-> camelCase) is non-conforming

### ISSUE THREAD

**Issue by jcready** [timostamm/protobuf-ts#396]
From [field_mask_util_test.cc](https://github.com/protocolbuffers/protobuf/blob/e8ae137c96444ea313485ed1118c5e43b2099cf1/src/google/protobuf/util/field_mask_util_test.cc#L69-L90):

```cpp
TEST_F(SnakeCaseCamelCaseTest, SnakeToCamel) {
  EXPECT_EQ("fooBar", SnakeCaseToCamelCase("foo_bar"));
  EXPECT_EQ("FooBar", SnakeCaseToCamelCase("_foo_bar"));
  EXPECT_EQ("foo3Bar", SnakeCaseToCamelCase("foo3_bar"));
  // No uppercase letter is allowed.
  EXPECT_EQ("#FAIL#", SnakeCaseToCamelCase("Foo"));
  // Any character after a "_" must be a lowercase letter.
  //   1. "_" cannot be followed by another "_".
  //   2. "_" cannot be followed by a digit.
  //   3. "_" cannot appear as the last character.
  EXPECT_EQ("#FAIL#", SnakeCaseToCamelCase("foo__bar"));
  EXPECT_EQ("#FAIL#", SnakeCaseToCamelCase("foo_3bar"));
  EXPECT_EQ("#FAIL#", SnakeCaseToCamelCase("foo_bar_"));
}


TEST_F(SnakeCaseCamelCaseTest, CamelToSnake) {
  EXPECT_EQ("foo_bar", CamelCaseToSnakeCase("fooBar"));
  EXPECT_EQ("_foo_bar", CamelCaseToSnakeCase("FooBar"));
  EXPECT_EQ("foo3_bar", CamelCaseToSnakeCase("foo3Bar"));
  // "_"s are not allowed.
  EXPECT_EQ("#FAIL#", CamelCaseToSnakeCase("foo_bar"));
}
```

## `FieldMask.toJson()` (snake_case -> camelCase)

The [existing implementation](https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/plugin/src/message-type-extensions/well-known-types.ts#L360-L366) fails tests 2 and 3 for `Any character after a "_" must be a lowercase letter.` as these do not throw errors:

```ts
// 2. "_" cannot be followed by a digit.
FieldMask.toJson({ paths: ['foo_3bar'] });

// 3. "_" cannot appear as the last character.
FieldMask.toJson({ paths: ['foo_bar_'] });
```

I believe this could trivially be fixed with the following change to [packages/plugin/src/message-type-extensions/well-known-types.ts](
https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/plugin/src/message-type-extensions/well-known-types.ts#L360-L366)

```diff
+                 const invalidFieldMaskJsonRegex = /[A-Z]|(_([.0-9_]|$))/g;
                  return message.paths.map(p => {
-                     if (p.match(/_[0-9]?_/g) || p.match(/[A-Z]/g))
+                     if (invalidFieldMaskJsonRegex.test(p))
```

## `FieldMask.fromJson()` (camelCase -> snake_case)

The [existing implementation](
https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/plugin/src/message-type-extensions/well-known-types.ts#L371-L386) fails the second expectation:
```ts
expect(FieldMask.fromJson('FooBar')).toEqual({ paths: ['_foo_bar'] });
// Expected $.paths[0] = 'foo_bar' to equal '_foo_bar'.
```

This failure is purely due to this one line but the git blame is so old and part of a commit simply titled "transferring to github.com" that it has become a classic Chesterton's Fence situation. https://github.com/timostamm/protobuf-ts/blob/3eea598471fb9c891c8b6da06bc1cbe18bc3457e/packages/plugin/src/message-type-extensions/well-known-types.ts#L382

Again, I believe this could be trivially fixed.

```diff
-                      return (sc[0] === "_") ? sc.substring(1) : sc;
+                      return sc; 
```

**Comment by hugebdu** [comment]
@timostamm any plans/thoughts to align it?
10x

**Comment by timostamm** [comment]
@hugebdu, we should match the C++ implementation. It's very likely that protobuf-es has the same issue. 
I'm strapped for time at the moment - contributions are most welcome. It should be fairly straight-forward to replicate the test cases and go from there.

**Comment by hugebdu** [comment]
@timostamm 
I can try submitting a PR, however that's a breaking change.
Do you want to add an option to control the field mask casing or this will be a major release?

**Comment by hugebdu** [comment]
@timostamm?
