### ISSUE TITLE
Buf deprecating custom remote plugins

### ISSUE THREAD

**Issue by Rsdutta** [timostamm/protobuf-ts#428]
Hi @timostamm 

Had a question about this plugin and its status on the buf registry. On the plugin page: https://buf.build/timostamm/plugins/protobuf-ts I saw the notice that buf will be deprecating community plugins such as this one. I also saw in an email mentioning that plugins can be added by opening an issue here: https://github.com/bufbuild/plugins?_hsmi=236314790 I was wondering about the plan moving forward here.

**Comment by timostamm** [comment]
Hey Rishov, would you mind filing an issue? :)

**Comment by Rsdutta** [comment]
https://github.com/bufbuild/plugins/issues/256 wasnt sure about the exact dependencies so will defer to you, thanks again!
