### ISSUE TITLE
toBinary(pete)      fromBinary(bytes);  cannot be found toBinary fromBinary function

### ISSUE THREAD

**Issue by heihuhei2013** [timostamm/protobuf-ts#429]
toBinary(pete)      fromBinary(bytes);  cannot be found toBinary fromBinary function

**Comment by timostamm** [comment]
Hey there, it seems you are having trouble getting this working. 

Try to keep it simple. Just follow the [quickstart](https://github.com/timostamm/protobuf-ts#quickstart).
