### ISSUE TITLE
Add option to generate protobuf oneofs as union types without oneofKind

### ISSUE THREAD

**Issue by j-boecker** [timostamm/protobuf-ts#440]
It would be very helpful to have an option to generate oneof representations to typescript unions without the "oneofKind" parameter.

Reasoning for this is that it is easier to work with the generated classes and switching from self-written typescript interfaces to Protobuf generated ones would require a rewrite of all checks with oneof types.
Especially because oneof is often used to declare optional nullable properties and this would make using nullish coalescing operators easier.

Example:

```proto
message OneofExample {
 oneof result { 
   string value = 1;
 }
}
```

```ts   
// with oneofKind
interface OneofExample {
 result: { oneofKind: "value"; value: string; } 
       | { oneofKind: undefined; };
}
let message: OneofExample;
if (message.result.oneofKind !== "value") {
 // return if value was not set
  return "Not set";
}
// or
return message.result.oneofKind === 'value' ? message.result.value : "Not set";

// without oneofKind
interface OneofExample {
 result: { value: string; } 
       | undefined
}
let message: OneofExample;
if (!message.result?.value) {
 // return if value was not set
  return "Not set";
}
// or
return message.result?.value ?? "Not set";
```

**Comment by jcready** [comment]
>Especially because oneof is often used to declare optional nullable properties

Normally the optional property is wrapped in another **message** like the [WellKnown "wrapper" types](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wrappers.proto) (specifically the [`google.protobuf.StringValue` message](https://github.com/protocolbuffers/protobuf/blob/1b1e399e2ec720cd93785ece148ec081255bd908/src/google/protobuf/wrappers.proto#LL109-L115) in your case). Or just use `optional` now that proto3 supports it.

**Comment by timostamm** [comment]
If I understand correctly, the option would make it impossible to distinguish between the two cases of this example:

```
message OneofExample {
 oneof result { 
   string value = 1;
   string alt = 2;
 }
}
```

Apologies, but we're not going to add an option for this behavior. 

For nullable fields, I recommend the wrapper types or the `optional` keyword, as @jcready suggests.
