### ISSUE TITLE
Enum add a way to enumerate the set of values.

### ISSUE THREAD

**Issue by james-lawrence** [timostamm/protobuf-ts#474]
pretty explanatory; currently no way to enumerate the list. have to do it manually.

**Comment by timostamm** [comment]
Take a look at [this article](https://www.petermorlion.com/iterating-a-typescript-enum/) to learn about TypeScript enumerations, and how to list values.

Note that protobuf-ts provides a couple of helper functions for this: `listEnumNames()`, etc. They are documented in [the manual](https://github.com/timostamm/protobuf-ts/blob/16ce40d32df2f847692543c83cff13bc80d6eece/MANUAL.md#enum-representation).

**Comment by james-lawrence** [comment]
how'd i miss that thanks. =)
