### ISSUE TITLE
Allow ignoreUnknownFields to be true as a default

### ISSUE THREAD

**Issue by tohyongcheng** [timostamm/protobuf-ts#489]
Our use case is that we use `fromJson` to parse JSON Strings (using canonical proto3 JSON formats) to Protobuf entities. We generate the protobuf-ts code stubs using protoc and we would like `ignoreUnknownFields to be set to true as a default) to prevent breaking changes when new fields are added to the message payloads during consumption.

We would want it to be available as a protoc option (e.g. allow_unknown=true from https://github.com/mitchellh/protoc-gen-go-json#options) so that we do not need to set it as an option in every `fromJson` call.

**Comment by timostamm** [comment]
I'd prefer to avoid plugin options that change runtime behavior. This is better solved in application logic. For example, consider the [TwirpFetchTransport](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#twirp-transport), which can serialize and parse JSON, but only has [one place](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#rpc-options) to configure JSON serialization. Consider a direct call:

```ts
const payload = "{}";

// assuming protobuf message "Foo"
const m = Foo.fromJsonString(payload);
console.log(m);
```

Versus defining a function that works on arbitrary messages:

```ts
function process<T>(type: IMessageType<T>, payload: string) {
  const m = type.fromJsonString({
    ignoreUnknownFields: true
  });
  console.log(m);
}

process(Foo, payload);
```
