### ISSUE TITLE
A problem about the callback for jspb.Map.forEach for 

### ISSUE THREAD

**Issue by jinyunshaobing** [timostamm/protobuf-ts#490]
What I see:
```
jspb.Map<string, string>.forEach(callback: (entry: string, key: string) => void, thisArg?: {} | undefined): void
```
I saw the entry and key here, but where is the value?
Map in TS is:
```
Map<string, string>.forEach(callbackfn: (value: string, key: string, map: Map<string, string>) => void, thisArg?: any): void
```

**Comment by timostamm** [comment]
Saw your issue https://github.com/protocolbuffers/protobuf-javascript/issues/163. This repository isn't the right one either. You have to open a PR against https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-protobuf
