### ISSUE TITLE
`timeout` vs `deadline` RPCOptions/GrpcWebOptions

### ISSUE THREAD

**Issue by staticdev** [timostamm/protobuf-ts#491]
When checking documentation of [RPCOptions](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#rpc-options) I see there is only `timeout` documented and it states if you pass a date it will be used as deadline. Then further in documentation says `GrpcWebOptions` extends `RPCOptions` with some other attributes but don't mention `deadline`.

When I check this example [here](https://github.com/timostamm/protobuf-ts/blob/master/packages/example-angular-app/src/app/grpcweb-unary/grpcweb-unary.component.ts#L28) I see:

```typescript
  readonly options: GrpcWebOptions = {
    baseUrl: 'http://localhost:5080',
    deadline: Date.now() + 2000,
   // ...
```

On the other side, when I keep `deadline` it works, but also after some tests with some sleep on the server I see this is just being ignored. 

To my view there is a problem in the example code or in the documentation. Am I missing something? 

In addition to that, for some reason I am always receiving a `503 Uncaught (in promise) RpcError: Service Unavailable` when I set a `timeout: Date.now() + 2000` right before the call not sure why. The application is responding to Kreya client in about 1s. Everything running on the same machine. When I remove the `Date.now() +` it works as expected also if I instead use `timeout: new Date(Date.now() + 2500)`.

**Comment by timostamm** [comment]
Thanks for pointing this out, @staticdev. The option was changed at some point, and I think the example was not updated. 

Could I ask you to open a PR with a fix in the example?

**Comment by timostamm** [comment]
Deadline is a set point in time, for example new Date(1676620004859).

A timeout is a duration in milliseconds, after which the request should terminate. For example 1000ms.

If you pass 1676620004859 + 200, it's a timeout that won't be seen for 1676620004859/1000/3600/24/365 = 53 years.

**Comment by staticdev** [comment]
> Thanks for pointing this out, @staticdev. The option was changed at some point, and I think the example was not updated.
> 
> Could I ask you to open a PR with a fix in the example?

https://github.com/timostamm/protobuf-ts/pull/494 as requested.
