### ISSUE TITLE
ts_nocheck is undocumented

### ISSUE THREAD

**Issue by Zamiell** [timostamm/protobuf-ts#493]
This command generates no output:

```bash
james@1qaz MINGW64 /d/Repositories/s2client-api-typescript/proto (main)
$ npx protoc --help | grep nocheck

james@1qaz MINGW64 /d/Repositories/s2client-api-typescript/proto (main)
$
```

**Comment by timostamm** [comment]
protoc is a compiler for protocol buffers. It does not output options of the plugins that you may have on your $PATH. 

It would be neat if it did! Maybe you could ask [the maintainers](https://github.com/protocolbuffers/protobuf)?
