### ISSUE TITLE
sourcemaps in npm release reference nonexistent files

### ISSUE THREAD

**Issue by tlstyer** [timostamm/protobuf-ts#50]
Webpack outputs warnings like this:
```
WARNING in ./node_modules/@protobuf-ts/runtime/build/es2015/assert.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/tmp/example/node_modules/@protobuf-ts/runtime/src/assert.ts' file: Error: ENOENT: no such file or directory, open '/tmp/example/node_modules/@protobuf-ts/runtime/src/assert.ts'
 @ ./node_modules/@protobuf-ts/runtime/build/es2015/index.js 41:0-89 41:0-89 41:0-89 41:0-89 41:0-89 41:0-89
```

`./node_modules/@protobuf-ts/runtime/build/es2015/assert.js` contains `"sources":["../../src/assert.ts"]`.  "../../src/assert.ts" does not exist in the npm release.

Similar warnings are output for the other files, too. Other sourcemaps have the same problem of referencing nonexistent files.

**Comment by tlstyer** [comment]
Note that this is found in the `1.0.11` release. There are no sourcemaps in the `2.0.0-alpha.4` release.

**Comment by tlstyer** [comment]
This was addressed in https://github.com/timostamm/protobuf-ts/issues/38. Sorry!

**Comment by timostamm** [comment]
Thanks for the report, @tlstyer. 

Seems like this should be back-ported. Just did that in release v1.0.12. 

2.0 should be fairly stable though, let me know if you notice something.
