### ISSUE TITLE
Update automatic install to target new Apple silicon release binaries

### ISSUE THREAD

**Issue by Swiftwork** [timostamm/protobuf-ts#505]
With version, 21+ protobuf releases precompiled binaries for Apple silicon https://github.com/protocolbuffers/protobuf/releases/tag/v21.0-rc1.

Currently, version 2.8.3 of protoc ignores the arch flag for darwin in the makeReleaseName function:

https://github.com/timostamm/protobuf-ts/blob/v2.8.3/packages/protoc/util.js#L174-L196

It would be great to have this updated.

**Comment by timostamm** [comment]
I agree. 

A small complication: The package allows to [install a specific version](https://github.com/timostamm/protobuf-ts/tree/v2.8.3/packages/protoc#installing-a-specific-version), and older releases of protoc aren't backfilled. So enabling the arm architecture is a breaking change. So the code path should only use arm for protoc versions that >=21 via a denylist or parsing the version. 

Happy to take a contribution!

**Comment by timostamm** [comment]
Hey @Swiftwork, with https://github.com/timostamm/protobuf-ts/pull/517 released in v2.9.0, this should be fixed. Please re-open if I'm wrong :slightly_smiling_face:
