### ISSUE TITLE
map<K, V> generated typing is inaccurate

### ISSUE THREAD

**Issue by samikytr** [timostamm/protobuf-ts#509]
For a `map<int32, int32>` protobuf-ts generates `{ [key: number]: number }` where I would expect it to generate `{ [key: number]: number | undefined }`, because there isn't guaranteed to be a value for every possible key in the map.

With the current behavior, accessing the map like `const value: number = myMap[123];` passes the type check, but value may actually be undefined instead of a number at runtime, which is a common cause of bugs.

**Comment by timostamm** [comment]
That would let you set `myMap[123] = undefined`, don't want to do that. 

Take a look at https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by samikytr** [comment]
> Take a look at https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

Ah, that's very good, but with this option I'm getting errors from the generated code when the map value is another message.

For example:
```protobuf
syntax = "proto3";
package example;

message MyMainMessage {
	map<int32, MySubMessage> my_map = 1;
}

message MySubMessage {
	int32 a = 1;
	int32 b = 2;
}
```

Gets me:
```
example_pb.ts:92:46 - error TS2345: Argument of type 'MySubMessage | undefined' is not assignable to parameter of type 'MySubMessage'.
  Type 'undefined' is not assignable to type 'MySubMessage'.

92             MySubMessage.internalBinaryWrite(message.myMap[k as any], writer, options);
                                                ~~~~~~~~~~~~~~~~~~~~~~~
```

I suppose I have to also enable `--ts_opt=ts_nocheck` to get around this?

**Comment by timostamm** [comment]
Yes, IIRC, ts_nocheck is the best option. I wish TypeScript would have fewer ways to do things sometimes 🙄
