### ISSUE TITLE
Bug: `bytes` incorrectly typed to `Uint8Array` but is `Buffer`

### ISSUE THREAD

**Issue by ben-xD** [timostamm/protobuf-ts#519]
Given a protobuf like:
```protobuf3
message Example {
    bytes body = 2;
}
```

protobuf-ts will generate:
```typescript
interface Example {
    body: Uint8Array;
}
```

However, `body` is a `Buffer`, not `Uint8Array`.

I noticed the error because superjson (I use that with tRPC) supports `Uint8Array` but **not** `Buffers`, and throws an error client side. I looked at the `example.body.__proto__`, and it looked like a `Buffer`, not a `Uint8Array`. To fix the issue, I mutated the body in `example.body = new Uint8Array(example.body.buffer)`. For example, you can compare `example.body.__proto__` with `Buffer.from(new Uint32Array()).__proto__`, they both extend `TypedArray`. A Uint8Array's prototype **is** the Typed Array, and extends `Object`.

I was confused because `example.body instanceof Uint8Array` returns true, so I assumed it was a `Uint8Array`. However, then I found that even `Buffer.from(new Uint32Array()) instanceof Uint8Array` returns true :facepalm:.

I think it would be nicer if they were actually `Uint8Array` instead of `Buffer`, but the correct type for what they are actually, would be `Buffer`?

Thanks :)

**Comment by ben-xD** [comment]
My 1 line workaround is to use zod:
```typescript
...
body: z.instanceof(Uint8Array).transform((val) => new Uint8Array(val.buffer)),
```

I initially had a 60 line workaround with tests.

**Comment by jcready** [comment]
The fact that `example.body instanceof Uint8Array` is true is proof that this isn't a bug with protobuf-ts. The issue seems to be that superjson is [entirely too strict](https://github.com/blitz-js/superjson/blob/0015b72acc200f4a0ed6865d48314f1d9e3ddd61/src/is.ts#L74-L88) Other superjson users seem to have [also run into this issue](https://github.com/blitz-js/superjson/issues?q=is%3Aissue+buffer+is%3Aclosed), here's a workaround: https://github.com/blitz-js/superjson/issues/181#issuecomment-1207498257

**Comment by timostamm** [comment]
@jcready is correct, this is an issue with superjson in combination with Node.js. There is not a single reference to `Buffer` in the runtime library or generated code of protobuf-ts, it only uses `UInt8Array` for bytes.

Node.js `Buffer` predates typed arrays, and `new Uint8Array` on Node.js will give you a `Buffer` that also implements `UInt8Array`. More details in the [Node.js docs](https://nodejs.org/api/buffer.html#buffers-and-typedarrays). 

Closing this, as there is nothing we can do in protobuf-ts.

**Comment by ben-xD** [comment]
> new Uint8Array on Node.js will give you a Buffer that also implements UInt8Array.

Oh interesting, thanks for explaining, @timostamm. I wonder why creating a new `Uint8Array` using the buffer (like in `example.body = new Uint8Array(example.body.buffer)`) fixes it. Nothing should change since it's still a Node `Uint8Array`, and the problem remains?

I saw the existing issues in superjson and tried their suggested workarounds - they did not work for me. Thankfully, my workaround works and I like using zod instead of configuring superjson a bit better.

**Comment by timostamm** [comment]
When parsing binary data, we're calling subarray(). That might end up having different result than the Uint8Array ctor. I don't think it is reasonable for protobuf-ts do do extra calls as a workaround for this specific case. This is between superjson and Node.js.
