### ISSUE TITLE
RpcError: unexpected response content type: application/grpc

### ISSUE THREAD

**Issue by jayden-qiu** [timostamm/protobuf-ts#585]
I use grpc-web + nginx + grpc-go.
nginx config is
```conf
        location / {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'X-Grpc-Web,Content-Type';

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            grpc_set_header Content-Type application/grpc;
            grpc_pass grpc://127.0.0.1:8080;
```
set grpc_set_header is must, but grpcweb-transport fail
![image](https://github.com/timostamm/protobuf-ts/assets/51039043/4c01530e-c1c4-4b23-917d-be67b9531c55)
there isn't exist application/grpc, what should I do ?

**Comment by jayden-qiu** [comment]
I try set metadata in grpc-go, but It doesn't work

**Comment by timostamm** [comment]
> there isn't exist application/grpc, what should I do ?

You cannot use gRPC in a web browser. gRPC and gRPC-web are two different things.

**Comment by jayden-qiu** [comment]
> > there isn't exist application/grpc, what should I do ?
> 
> You cannot use gRPC in a web browser. gRPC and gRPC-web are two different things.

![image](https://github.com/timostamm/protobuf-ts/assets/51039043/f2214e61-6cee-4450-8dca-646336e7124f)
but in network tab, it can response data, it looks like grpc-web-format.js bug

**Comment by jcready** [comment]
A content-type of `application/grpc` isn't a valid grpc-web content-type. Please read the link in the comment right above the red box in your first screenshot: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2

> Content-Type
> 
> 1. application/grpc-web
>   * e.g. application/grpc-web+[proto, json, thrift]
>   * the sender should always specify the message format, e.g. +proto, +json
>   * the receiver should assume the default is "+proto" when the message format is missing in Content-Type (as "application/grpc-web")
> 2. application/grpc-web-text
>   * text-encoded streams of “application/grpc-web”
>   * e.g. application/grpc-web-text+[proto, thrift]

It doesn't seem like nginx actually provides support for grpc-web, only grpc. You'll need something like envoy to provide that support.

**Comment by jayden-qiu** [comment]
ok
