### ISSUE TITLE
Whether vue3 ssr is supported？

### ISSUE THREAD

**Issue by captain-jack666** [timostamm/protobuf-ts#587]
Excuse me！How to be compatible with vue3 ssr? Why do I get an error in ssr request: fetch is not defined

**Comment by jcready** [comment]
In the [manual it says](https://github.com/timostamm/protobuf-ts/blob/main/MANUAL.md#running-in-nodejs):

> If you are using the grpcweb-transport or twirp-transport, you probably have to polyfill the fetch API. See the README files of the transport packages for more information.

And [for grpcweb-transport](https://github.com/timostamm/protobuf-ts/blob/main/MANUAL.md#grpc-web-transport):

> **Note:** This transport requires the fetch API (`globalThis.fetch` and `globalThis.Headers`). For Node.js, use the polyfill [node-fetch](https://github.com/node-fetch/node-fetch).

**Comment by captain-jack666** [comment]
@jcready 

Sorry, I didn't notice this MANUAL.md file before. Thanks for your help.
