### ISSUE TITLE
Why is a descriptor.ts generated?

### ISSUE THREAD

**Issue by EricDotSmith** [timostamm/protobuf-ts#588]
Hello, when I run

`npx protoc --ts_out . --proto_path proto proto/project.proto`

I get

- project.client.ts
- project.ts
- _**descriptor.ts**_

_**descriptor.ts**_ doesn't seem to be needed by either project.ts or project.client.ts. My question is why is it generated? Is there a role for this file that I'm not seeing?

**Comment by timostamm** [comment]
Hey Eric, 

I just ran the [quickstart](https://github.com/timostamm/protobuf-ts#quickstart) and end up with this tree:

```bash
$ tree -L 2 --noreport
.
├── msg-readme.ts
├── node_modules
│   ├── @protobuf-ts
│   └── typescript
├── package-lock.json
├── package.json
└── protos
    └── msg-readme.proto
```

I don't know where descriptor.ts is coming from in your case. If you think it is a bug, we'll need a bit more details 🙂

**Comment by EricDotSmith** [comment]
So I ran the quick start, then used my project.proto and annotations.proto. In annotations.proto, it uses some of the google api stuff. I'm assuming its just the way protobuf-ts parses and generates the .ts files, but I don't really need the descriptor.ts that it generates. 


```
.
├── node_modules
│   ├── @protobuf-ts
│   └── typescript
├── package-lock.json
├── package.json
└── protos
    ├── annotations.proto
    ├── google
    │   └── api
    │       ├── annotations.proto
    │       └── http.proto
    └── project.proto
```

**Comment by timostamm** [comment]
This might be related to the logic here: https://github.com/timostamm/protobuf-ts/blob/3a7ce47d43113d1a80cacd0ae70630b3727eda3e/packages/plugin/src/protobufts-plugin.ts#L348-L373

It should omit descriptor.proto in your case. 

This needs more investigation.

**Comment by EricDotSmith** [comment]
Just a little bit more info that may help.

I installed `npm install @protobuf-ts/plugin`

Command I use: `npx protoc --ts_out out --proto_path . project.proto`

This gives me:

1. **_project.client.ts_**
2. **_project.ts_**
3. **_google/protobuf/descriptor.ts_** (this is the unnecessary one)

In **_project.proto_**, there is a 
```proto
syntax = "proto3";

import "annotations.proto";
...
```

Then in **_annotations.proto_**, there is a
```proto
syntax = "proto3";

package google.api;

import "google/api/http.proto";
import "google/protobuf/descriptor.proto";

option go_package = "google.golang.org/genproto/googleapis/api/annotations;annotations";
option java_multiple_files = true;
option java_outer_classname = "AnnotationsProto";
option java_package = "com.google.api";
option objc_class_prefix = "GAPI";

extend google.protobuf.MethodOptions {
  // See `HttpRule`.
  HttpRule http = 72295728;
}

```

The generated **_project.client.ts_**, has what's expected like so
```ts
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ApiService } from "./project";
...
```

Finally in **_project.ts_**, it has this
```ts
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
...
```

For now I'm just ignoring the file, but yeah need to investigate the logic you posted to see why its generating an unnecessary file.

**Comment by timostamm** [comment]
We need to switch our plugin from `@protobuf-ts/plugin-framework` to `@bufbuild/protoplugin`.  This will provide much better capabilities to detect what needs to be generated, and better capabilities to conditionally generate. 

Given time constraints, it makes little sense to put work into a fix right now with the current plugin.
