### ISSUE TITLE
prefer system installed protoc

### ISSUE THREAD

**Issue by someone1** [timostamm/protobuf-ts#60]
We have a monorepo and use protoc for more than our web client which is why it's installed and configured in our development container systemwide. As such, the `protoc` installed into our `node_modules/.bin` folder from `@protobuf-ts/plugin` is getting priority in our build scripts and is missing a bunch of includes we rely on. Is there a way to disable installing this dependency and/or have a config option to prefer the system-wide installed version?

our "build" scripts are scripts defined in our `package.json`

**Comment by timostamm** [comment]
Thanks for the report. There is no built-in option to support this.

@protobuf-ts/protoc is already looking at the package.json. If `pkg.config.protocVersion` is set, it tries to install protoc in this version. 

It should be possible to add a second key `pkg.config.useProtocPath`. If set, @protobuf-ts/protoc could execute protoc from this path, and not install it's own version at all. 

Would this solve the issue?

**Comment by someone1** [comment]
Hmm - I think that'd be fine, I was otherwise thinking to auto-detect if protoc is already found in the $PATH (sans the `node_modules/.bin` directory) and use that before resorting to installing it.

**Comment by timostamm** [comment]
Agreed, preferring $PATH is better. 

Users could opt out of $PATH and ensure installation by setting `pkg.config.protocVersion` explicitly. 

I think [this commit](https://github.com/timostamm/protobuf-ts/commit/f674ac460a845eabc7b6cc4eb626a1552b537841) should do it. Do you have a way to test this?

**Comment by someone1** [comment]
just ran it, seems to have done the trick!

**Comment by timostamm** [comment]
👍 

Released in v2.0.0-alpha.11

**Comment by gganley** [comment]
Hello,

Is it possible to backport this fix to v1.x?

**Comment by timostamm** [comment]
Could you try updating @protobuf-ts/protoc ? 

```shell
npm i @protobuf-ts/protoc@next
```

This updates the "protoc" package only and keeps the 1.x version for everything else. 

I am pretty sure that the new version of the "protoc" package should work just fine, but it would help a lot if you could confirm. 

If this does not cause any problems, I can backport and publish as 1.x.

**Comment by gganley** [comment]
Yes that did work! Thanks for the help.
