### ISSUE TITLE
How to set limited headers in CORS?

### ISSUE THREAD

**Issue by hengyunabc** [timostamm/protobuf-ts#603]
The gRPC web service is deployed at `aaa.test.com`, and the website being accessed by users is `bbb.test.com`.

When send a request to `aaa.test.com` from the browser, I want to include cookie information. So, on the server-side of `bbb.test.com`, I set `Access-Control-Allow-Credentials` to `true` and also set `Access-Control-Allow-Origin` to `aaa.test.com`.

However, there is another issue. When `Access-Control-Allow-Credentials` is set to `true`, the server-side cannot set `Access-Control-Allow-Headers` to `*`. It can only specify limited headers by `Access-Control-Allow-Headers`.

Therefore, when making the request in JavaScript, I can only use limited headers. Does protobuf-ts support setting limited headers? I tried the code below, but it doesn't seem to work.

```js
  const customHeaders: [string, string][] = [
    ['Content-Type', 'application/json'],
    ['Authorization', 'Bearer token'],
  ];

  let transport = new GrpcWebFetchTransport({
    baseUrl: window.location.origin,
    fetchInit: { headers: customHeaders },
  });
```

The grpc web request still comes with the following header

```
    "pragma": "no-cache",
    "sec-ch-ua": "\"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
```

**Comment by timostamm** [comment]
You cannot include credentials with `Access-Control-Allow-Origin: *`. You have to allow specific origins instead.

This is unrelated to protobuf-ts - it's how browsers handle cross-origin requests. You will not be able to work around this with simple requests or no-cors mode.

**Comment by hengyunabc** [comment]
@timostamm Thank you for your reply. 

Sorry, I made a mistake above. Setting `Access-Control-Allow-Headers` to `*` is not allowed.

Currently I set `Access-Control-Allow-Origin` to `aaa.test.com`.

I tested that if use the fetch api, you can specify headers and there will be no extra headers. At the same time, set `Access-Control-Request-Headers: client-id` on the server side, so that the server can handle the request correctly.


```
fetch("https://aaa.test.com/servic/method", {
   "headers": {
     "accept": "application/grpc-web-text",
     "client-id": "xxxx",
   }
   "
```

Is there any way to control `headers` when using `protobuf-ts`?

**Comment by timostamm** [comment]
> At the same time, set Access-Control-Request-Headers: client-id on the server side, so that the server can handle the request correctly.

That's incorrect. `Access-Control-Request-Headers` is a header sent by the browser automatically for preflight requests. 

You'll have to spend some time to read up on the documentation for CORS, run some examples yourself, and set up CORS correctly on your server. I highly recommend to use a CORS middleware if available.

The gRPC-web transport just uses fetch. It adds a couple of protocol-specific headers that you should not remove, otherwise your gRPC-web requests are broken. You can add your own headers via RPC options, see the manual.

**Comment by jcready** [comment]
@hengyunabc the grpc-web transport must set the [`Content-Type` request header to `application/grpc-web-text` or `application/grpc-web+proto`](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2). This is probably the bare minimum headers your server will need to respond with to work with CORS grpc-web requests:

```
Access-Control-Allow-Methods: OPTIONS, POST
Access-Control-Allow-Headers: accept, content-type, grpc-timeout, x-grpc-web
Access-Control-Expose-Headers: grpc-message, grpc-status
```

**Comment by hengyunabc** [comment]
Thanks for replies, I made a stupid mistake.


`Access-Control-Request-Headers` are sent by the browser to the server.

`Access-Control-Allow-Headers` is sent by the server to the browser.

The browser will send the following request header to the server:

```
Access-Control-Request-Headers: bx-v,cache-control,client-id,content-type,pragma,x-grpc-web
```

So server needs to return:

```
Access-Control-Allow-Headers: bx-v,cache-control,client-id,content-type,pragma,x-grpc-web
```

If `Access-Control-Allow-Headers: *` is returned, or `Access-Control-Allow-Headers: client-id` is returned, it will fail.
