### ISSUE TITLE
TypeScript linting/compiler issues with generated client

### ISSUE THREAD

**Issue by EricDotSmith** [timostamm/protobuf-ts#604]
The TypeScript compiler kept giving me errors in **_project.client.ts_**. As such, I wasn't able to immediately compile the generated client with my **_tsconfig.json_** until I removed the noUncheckedIndexAccess property:

```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "checkJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    // "noUncheckedIndexedAccess": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": [
    ".eslintrc.cjs",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.cjs",
    "**/*.mjs"
  ],
  "exclude": ["node_modules"]
}

```

After doing that I was able to compile the code, however there were still a bunch of linting errors in the **_project.ts_** file, to remedy this I had to add this to my **_.eslintrc.cjs_**:

```cjs
   "@typescript-eslint/ban-tslint-comment": "warn",
    "@typescript-eslint/no-unsafe-argument": "warn",
    "@typescript-eslint/no-empty-interface": "warn",
    "@typescript-eslint/no-unsafe-enum-comparison": "warn",
    "@typescript-eslint/prefer-for-of": "warn",
    "prefer-const": "warn",
```

The question for me becomes, is there a way to not have to change my linter/compiler options just to get the generated client to work in my project?

**Comment by jcready** [comment]
According to the [manual](https://github.com/timostamm/protobuf-ts/blob/main/MANUAL.md#the-protoc-plugin) you should be able to use the `ts_nocheck` and `eslint_disable` options:

```
npx protoc \
  --ts_out src/generated/ \
  --ts_opt ts_nocheck \
  --ts_opt eslint_disable \
  --proto_path protos \
  protos/my.proto 
```

**Comment by EricDotSmith** [comment]
> According to the [manual](https://github.com/timostamm/protobuf-ts/blob/main/MANUAL.md#the-protoc-plugin) you should be able to use the `ts_nocheck` and `eslint_disable` options:
> 
> ```
> npx protoc \
>   --ts_out src/generated/ \
>   --ts_opt ts_nocheck \
>   --ts_opt eslint_disable \
>   --proto_path protos \
>   protos/my.proto 
> ```

This solved the issue for me, thank you!
