### ISSUE TITLE
Provide and detect well known types

### ISSUE THREAD

**Issue by someone1** [timostamm/protobuf-ts#61]
I have a SPA that will utilize multiple gRPC clients for various APIs. My APIs use many well known types and imports which end up generating the same dependencies but aren't deduped or anything so I get duplicative 100K+ code bundled into my app for each api I import and use.

Would it be possible to provide a `@protobuf-ts/google` package that contains some well known protobuf imports and the generator can detect and use this package anytime any of them are utilized? 

Imports that I find myself using across APIs:

```
import "google/protobuf/any.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/resource.proto";
import "google/api/field_behavior.proto";
import "google/rpc/status.proto";
import "google/type/date.proto";
```

This may also be due to my mono-repo design, instead of generating clients directly into my SPA app folder, I do so in a general `genclients` meant to provide each client as a separate package.

```
protos/
     api1.proto
     api2.proto
genclients/
      api1/
            /src
            /dist
            package.json
      api2/
            /src
            /dist
            package.json
apps/
      spa1/ (imports api1 only)
            /src
            package.json
      spa2/ (imports api1 & api2)
            /src
            package.json
```

I'll be moving my generator scripts to be application-specific and generate the clients into the app folders directly to get around this for now - so instead of my apps not being able to detect/dedup common dependencies, I'll just be duplicating the generated clients across apps in my repository.

**Comment by timostamm** [comment]
> Would it be possible to provide a `@protobuf-ts/google` package that contains some well known protobuf imports and the generator can detect and use this package anytime any of them are utilized?

Certainly possible, yes. I considered this idea previously but decided against it because it only solves this issue for well-known-types and there are [many other proto files](https://github.com/googleapis/googleapis/tree/master/google) that would not benefit. Taking the increased complexity and maintenance into account, it seemed to be the better choice to keep it simple.

I'd say your workaround is the way to go. I have a similar use case where two apis use well-known-types, but also common proto files. I simply generate code into each app. Directory layout looks like this:

```
protos/
     api1.proto
     api2.proto
     common.proto
apps/
      spa1/ 
            /src
            /src-gen/api1.ts
            /src-gen/common.ts
            package.json
      spa2/ 
            /src
            /src-gen/api1.ts
            /src-gen/api2.ts
            /src-gen/common.ts
            package.json
```

Hope this works for you. Thanks for the report and please reopen if necessary.

**Comment by someone1** [comment]
makes sense - thanks for the feedback!

Might be a "me" issue - but I keep getting errors via Jest when I moved it out of a package into my client code - do you have any suggestions on tweaks to the jest config required to make code generated from this package to work in Jest? I have it working otherwise for all my other tests (all TypeScript as well).

```js
// jest.config.js
module.exports = {
  preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
  setupFiles: ['<rootDir>/tests/setupJest.ts'],
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!(lodash-es|vuetify))'],
  moduleNameMapper: {
    '@clients/(.*)$': '<rootDir>/src-gen/$1',
  },
};
```

```bash
 Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: Unexpected token } in JSON at position 514
        at JSON.parse (<anonymous>)

      at parse (node_modules/tsconfig/src/tsconfig.ts:195:15)
      at readFileSync (node_modules/tsconfig/src/tsconfig.ts:181:10)
      at Object.loadSync (node_modules/tsconfig/src/tsconfig.ts:151:18)
      at find (node_modules/vue-jest/lib/load-typescript-config.js:33:39)
      at loadTypescriptConfig (node_modules/vue-jest/lib/load-typescript-config.js:73:26)
      at compileTypescript (node_modules/vue-jest/lib/compilers/typescript-compiler.js:9:20)
      at processScript (node_modules/vue-jest/lib/process.js:23:12)
      at Object.module.exports [as process] (node_modules/vue-jest/lib/process.js:42:18)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:453:35)
```

**Comment by timostamm** [comment]
Maybe Jest's error message is misleading. I don't think there are syntax errors in the generated code. 

The details...

> ```
>    SyntaxError: Unexpected token } in JSON at position 514
>        at JSON.parse (<anonymous>)
>
>      at parse (node_modules/tsconfig/src/tsconfig.ts:195:15)

... look like a tsconfig.json file cannot be parsed?

I'd try to isolate this tsconfig.json and looks for syntax errors there.

**Comment by someone1** [comment]
I'll look into that but I'm not sure if that's the problem - the only tests that fail are the ones that import from the generated code. It worked prior to moving them from separate packages and the other 10s of test I have that don't import from the generated code compiles/pass without issue. I can otherwise compile the code without issue and see no eslint/IDE errors.

Please let me know if you can think of anything else that may be causing issues or configurations required specific to Jest!

**Comment by timostamm** [comment]
I have very little experience with Jest, unfortunately...  Hope you can isolate it.

It is possible that a specific tsconfig.json is only interpreted when the compiler enters the directory. Which happens when you import a file. And this line from your stack trace really seems to JSON.parse invalid json. 

https://github.com/TypeStrong/tsconfig/blob/master/src/tsconfig.ts#L195

**Comment by someone1** [comment]
ahh - you were exactly right - somehow was only being pulled when importing generated client code and while mucking with my linters I had a trailing comma in the tsconfig file that went undetected. 

All working fine, thanks for helping out!
