### ISSUE TITLE
Global `Object` is not referenced when there is a message named Object.

### ISSUE THREAD

**Issue by lesomnus** [timostamm/protobuf-ts#610]
I compiled [Argo Workflows v1alpha1](https://github.com/argoproj/argo-workflows/blob/da97f59375fdd4da63d66eeea7225e71d5276d5f/pkg/apis/workflow/v1alpha1/generated.proto#L1178-L1179) messages and there is a message named 'Object', which causes this issue:
```
Property 'keys' does not exist on type 'Object$Type'.ts(2339)
```
 in the generated code:
```ts
...
        /* map<string, github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.Artifact> artifacts = 2; */
        for (let k of Object.keys(message.artifacts)) {  // <- HERE
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
...
```
 I think it should be:
```diff
        for (let k of Object.keys(message.artifacts)) {
-        for (let k of Object.keys(message.artifacts)) {
+        for (let k of globalThis.Object.keys(message.artifacts)) {
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
```

I don't know this is related with the #579

**Comment by timostamm** [comment]
I think this might be a different issue than https://github.com/timostamm/protobuf-ts/issues/579. You are generating speed-optimized code, and it looks like it's missing a `globalThis`. This should be an easy fix, PRs welcome.

**Comment by lesomnus** [comment]
@timostamm Please review #611
