### ISSUE TITLE
2.9.2 not working with 'exactOptionalPropertyTypes: true'

### ISSUE THREAD

**Issue by steida** [timostamm/protobuf-ts#614]
"Type 'EncryptedMessage$Type' is not assignable to type 'IMessageType<any>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.\n  Types of property 'messagePrototype' are incompatible.\n    Type 'Readonly<{}> | undefined' is not assignable to type 'Readonly<{}>'.\n      Type 'undefined' is not assignable to type 'Readonly<{}>'.",

2.9.1 is OK

**Comment by jcready** [comment]
This was my fault as there was a different property type definition between the `IMessageType` interface and the `MessageType` class which implements it for the newly added `messagePrototype` field. I apologize for the breakage and I've opened a PR which should fix the issue.
