### ISSUE TITLE
Vite cannot found module

### ISSUE THREAD

**Issue by kingsley8524267** [timostamm/protobuf-ts#633]
generate command: 
```
npx protoc --ts_out src/protos --ts_opt long_type_string --proto_path . grpc.proto
```

ts code:
```
import * as grpcWeb from 'grpc-web';
import {GatewayClient} from '@/protos/GrpcServiceClientPb';
import {LoginRequest} from "@/protos/grpc_pb";


  const grpc = new GatewayClient('http://localhost:50051');
    grpc.login(new LoginRequest(), {}, (err: grpcWeb.RpcError, response) => {
        if (err) {
            console.error('Error:', err.message);
            return;
        }
        console.log('success', response.getStatus(), response.getMessage(), response.getData())
        // Handle response
    });
```

![image](https://github.com/timostamm/protobuf-ts/assets/133184499/335e5b3c-451c-4f36-9d63-392565c6d78a)

**Comment by kingsley8524267** [comment]
Files of generated
![image](https://github.com/timostamm/protobuf-ts/assets/133184499/da3e1929-4dc9-43e6-b852-bafe8125c53a)

**Comment by jcready** [comment]
The library/code-generator doesn't produce code that requires the consume to use `new`, nor does it generate files with `_pb.js` unless explicitly told to do so, so I'm guessing you've filed an issue with the wrong repo.
