### ISSUE TITLE
Invalid typescript in descriptor.ts

### ISSUE THREAD

**Issue by cirvladimir** [timostamm/protobuf-ts#634]
I'm generating proto for a file that uses `descriptor.proto`, which causes google/descriptor.ts to be generated. However, that file contains invalid typescript, which results in compilation issues.

There are about 10-20 errors in this fashion:

```
static fromObject(data: {
    file?: ReturnType<typeof FileDescriptorProto.prototype.toObject>[];
}): FileDescriptorSet {
    const message = new FileDescriptorSet({
        file: data.file.map(item => FileDescriptorProto.fromObject(item))
    });
    return message;
}
```

Note how the `file` field is nullable, however there is no null check in the function.

**Comment by jcready** [comment]
This library/code-generator doesn't use `.fromObject()` or `.toObject()` so I'm guessing you've filed an issue with the wrong repo.
