### ISSUE TITLE
Fails to download v27.0-rc1 (which was just released)

### ISSUE THREAD

**Issue by jraymakers** [timostamm/protobuf-ts#645]
Protocol Buffers v27.0-rc1 was just [released](https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1).

@protobuf-ts/protoc tries to download it from (for example):
```https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc1-osx-aarch_64.zip```
but the actual URL is:
```https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc-1-linux-x86_64.zip```
(Note the `-` between `rc` and `1`.)

Example error output:
```
@protobuf-ts/protoc failed to download protoc v27.0-rc1. 
Did you misspell the version number? The version number must look like "3.0.12", without a leading "v".
Error: HTTP 404 for https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc1-osx-aarch_64.zip
```

**Comment by mss30** [comment]
Did anyone find any workaround?

**Comment by rontrolard** [comment]
I just made this sorta-ugly pr for it: https://github.com/timostamm/protobuf-ts/pull/647

**Comment by kyleparrott** [comment]
As a temporary workaround you should be able to pin to the previous protoc version in your `package.json` :
```
"config":  { 
   "protocVersion": "26.1"
}
```

**Comment by saltyseabastard** [comment]
> As a temporary workaround you should be able to pin to the previous protoc version in your `package.json` :
> 
> ```
> "config":  { 
>    "protocVersion": "26.1"
> }
> ```

This didn't work for me, I tried putting the config line into all the package.jsons, but no dice. Which one specifically needs it?

**Comment by timostamm** [comment]
Hm, it looks like the latest release candidate was not published as a pre-release version. 

See:
- https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1
- https://github.com/protocolbuffers/protobuf/releases/tag/v25.0-rc1

It's an issue that we fail to install the release, but I don't think we should install a release candidate by default in the first place.

Unfortunately, I'm not sure that there is a good option to skip v27.0-rc1. We would have to make an API call, filter releases that look like a pre-release, and probably also have to semver-sort ourselves.

It would be best if this would be fixed upstream by marking v27.0-rc1 as a pre-release. I'm sure other tools that automatically fetch `protoc` will run into this issue that an unstable pre-release version is installed (or tried to).

**Comment by rontrolard** [comment]
corresponding issue in protobuf: https://github.com/protocolbuffers/protobuf/issues/16571

**Comment by timostamm** [comment]
The upstream release has been marked as a pre-release, see https://github.com/protocolbuffers/protobuf/issues/16571#issuecomment-2066779451.

This should resolve this issue as well. LMK if that's not the case.
