### ISSUE TITLE
Object generated by protobuf-ts seems not support TWO-WAY binding in vue.

### ISSUE THREAD

**Issue by jmzwcn** [timostamm/protobuf-ts#648]
Object generated by protobuf-ts seems not support TWO-WAY binding in vue.

**Comment by timostamm** [comment]
@jmzwcn, protobuf-ts generates simple objects. I encourage you to try two-way binding in Vue with simple objects first, then pull in protobuf-ts in a separate step. If you still think protobuf-ts should change behavior after that, please explain how and why.

**Comment by jmzwcn** [comment]
could you please provide an example for how to two-way binding in vue?  ^_^

**Comment by jmzwcn** [comment]
let card:Card=Card.create()

**Comment by jmzwcn** [comment]
thanks!

**Comment by jcready** [comment]
File an issue with Vue.
