### ISSUE TITLE
Twirp v7?

### ISSUE THREAD

**Issue by delaneyj** [timostamm/protobuf-ts#69]
It appears you support v5 but [v7](https://twitchtv.github.io/twirp/docs/spec_v7.html) is out and the other [currently available library won't be supporting it](https://github.com/larrymyers/protoc-gen-twirp_typescript/issues/53).

**Comment by timostamm** [comment]
From https://twitchtv.github.io/twirp/docs/spec_v7.html#differences-with-v5

> - Twirp URLs in v5 could only have the "/twirp" prefix. In v7 they can have any arbitrary prefix or no prefix. 
> - Error responses with code resource_exhausted in v5 had the HTTP status 403. In v7 they have status 429. 

Twirp transport already allows arbitrary or no prefix. 

The mapping of between Twirp and HTTP status codes is actually only relevant for servers: 

> When a server responds with the given error code, it must set the corresponding HTTP Status Code for the response.

We do not look at the HTTP status code, we use the status code in the [Twirp error response](https://twitchtv.github.io/twirp/docs/spec_v7.html#errors) and expose it in the RpcError.

This means that protobuf-ts is already Twirp v7 compliant. If I am missing something, please reopen.
