### ISSUE TITLE
Support package exports?

### ISSUE THREAD

**Issue by shrinktofit** [timostamm/protobuf-ts#70]
`"module"` in `package.json` is not an official field. To consume this package as ESM in Node, one should use `"exports"`, as stated in https://nodejs.org/api/packages.html

**Comment by timostamm** [comment]
Thanks for the report. 

This means ini all package.json we publish, the following key:

https://github.com/timostamm/protobuf-ts/blob/26c0ddf1e032920a27f61f9f50d798f02061a837/packages/runtime/package.json#L24

Should be replaced by:

```json
  "exports": "./build/es2015/index.js", 
```

Correct?

**Comment by shrinktofit** [comment]
I think they can both exist.

**Comment by timostamm** [comment]
Added ` "exports": "./build/es2015/index.js"`, but getting `SyntaxError: Unexpected token 'export'` when trying to require something from the package.

Right now, "module" works with bundlers and "main" works with node. Once there is a way to merge this in a single build I will gladly update. But I guess we are not there yet.

**Comment by shrinktofit** [comment]
@timostamm  The error happened since node treats it as CommonJS.

To consume this package both as ESM and CommonJS, by Node.

- Files under `build/es2015/` should have extension '.mjs', and import specifiers in these files should specify extension.
  
  The reason is how Node recognize ESM: '.mjs' or `"type: module"` in package.json. But the later would distort CommonJS modules so it's better to use '.mjs'.

  I noticed that `index.js` contains import specifiers self-referenced. They should be relative. For example `export { base64decode, base64encode } from '@protobuf-ts/runtime/build/es2015/base64';` should be `export { base64decode, base64encode } from './base64.mjs';` since `exports` field does not contain `build/es2015/base64` subpath.
- `package.json`
  
  ```json5
  "exports": {
      ".": {
        "import": "./build/es2015/index.mjs",
        "require": "./build/commonjs/index.cjs"
      }
  }
  ```

I've been test above for both ESM and CommonJS. Reference only.

Besides, I guess `exports`(Node) and `module`(Bundler) can both exist. But I have not been test yet.

**Comment by timostamm** [comment]
Thanks for the research and write-up. 

FYI: the builds are created with the typescript compiler. It is run two times, once building ES2015 modules, once building commonjs and type declarations:

https://github.com/timostamm/protobuf-ts/blob/2f14eba689dc839a73daf87b0e0431d00182eeba/packages/runtime/Makefile#L7-L12

The compiler has no option to set the file suffix, so it is not possible to change to suffix to `.mjs` easily. Creating `.mjs` would also mean that we have to publish exactly the same files twice, just with a different suffix. 

The overriding package.json with `type: module` of rollup.js seems like a decent workaround. If this means the commonjs build can be dropped and just the ES2015 build alone is sufficient for bundlers as well as node, I would consider this a very welcome improvement.
