### ISSUE TITLE
Generated code for "google/protobuf/any.proto"

### ISSUE THREAD

**Issue by rhlsthrm** [timostamm/protobuf-ts#78]
The generated client code for a proto file with `import "google/protobuf/any.proto";` imports a file that does not exist. How do I make the `any` file generate as part of the generated code?

**Comment by timostamm** [comment]
Are you using the parameter "generate_dependencies"?

> By default, only the PROTO_FILES passed as input to protoc are generated,
not the files they import. Set this option to generate code for dependencies
too.


You can set plugin parameters like this:

```
protoc --ts_opt generate_dependencies
```

**Comment by rhlsthrm** [comment]
I am. I'm using this command:

```
protoc --experimental_allow_proto3_optional --ts_opt server_grpc,client_promise,generate_dependencies --proto_path proto --ts_out ./src/grpc proto/*.proto
```

I've tried a few times and it never generates the dependencies, the generated client imports

```
import { Any } from "./google/protobuf/any";
```

But the file does not exist.

**Comment by rhlsthrm** [comment]
I've worked around it by copy-pasting the Any.proto dependency into my sources but of course, I would much rather not do that.

Versions:
```
"@protobuf-ts/plugin": "2.0.0-alpha.11",
"@protobuf-ts/protoc": "2.0.0-alpha.11",
```

**Comment by timostamm** [comment]
Thanks for the detailed info. 

This was bug #59 and the fix wasn't released yet.

2.0.0-alpha.12 is just released and fixes this problem. 

Tested with:

```shell
npm init -y
npm i @protobuf-ts/plugin@next
curl https://raw.githubusercontent.com/timostamm/protobuf-ts/master/packages/test-fixtures/wkt-any.proto > wkt-any.proto
npx protoc -I . --ts_out . --ts_opt generate_dependencies,optimize_code_size wkt-any.proto
```

`google/protobuf/any.ts` is now generated:

![screenshot](https://user-images.githubusercontent.com/4289451/105877793-a20d9e00-6000-11eb-90bb-2daea4cf109a.png)

**Comment by timostamm** [comment]
Note that parameter "server_grpc" is now "server_grpc**1**" :)

https://github.com/timostamm/protobuf-ts/blob/master/CHANGELOG.md#v200-alpha12

Please reopen if it doesn't work.

**Comment by rhlsthrm** [comment]
Excellent! It worked for me! Thanks for the quick fix.
