### ISSUE TITLE
Improve support for the `node-fetch` polyfill

### ISSUE THREAD

**Issue by timostamm** [timostamm/protobuf-ts#81]
'node-fetch' is great but does not use what wg streams API `ReadableStream` for `response.body`. 

See https://github.com/node-fetch/node-fetch/issues/754

This means that @protobuf-ts/grpcweb-transport will not work on node, even with the `node-fetch` polyfill.

**Comment by andrewbeckman** [comment]
Hi @timostamm I noticed that this was fixed for grpc web but it seems like it's still an issue for twirp. I'm happy to do to the work to get it working for Twirp too unless you have the time to quickly knock it out. Any pointers on what needs addressing?

**Comment by andrewbeckman** [comment]
After doing some more digging, I'm running into a `FileReader.readAsArrayBuffer is not implemented` error from my React Native app when `arrayBuffer` is called.
