### ISSUE TITLE
generate_dependencies for well-known-types

### ISSUE THREAD

**Issue by julianklose** [timostamm/protobuf-ts#87]
Can you make it more clear in the manual that it is crucial to add "--ts_opt generate_dependencies" when using well-known-types? It took me some time to figure it out today.

**Comment by timostamm** [comment]
Have added a prominent note in the manual. Thanks for your feedback!


Just FYI from google/protobuf/compiler/plugin.proto:

> The .proto files that were explicitly listed on the command-line.  The
> code generator should generate code only for these files.

I understand that in most cases you want to generate code for the dependencies as well.  
I would really like to flip the behaviour, but am very wary of breaking with the specs.
