### ISSUE TITLE
A big, huge, infinite THANK YOU for your work.

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#88]
A big, huge, infinite THANK YOU for your work.

I took the liberty of adding this project here: https://github.com/grpc-ecosystem/awesome-grpc/pull/137.

**Comment by Bluskript** [comment]
I also would like to thank you for everything you have done. This is probably the most well-designed protobuf implementation for javascript i've seen yet, especially with the code size. Finally, no more enormous runtimes!
