### ISSUE TITLE
'illegal tag: field no 0 wire type 1' exception when parse message with FromBinary.

### ISSUE THREAD

**Issue by hamming** [timostamm/protobuf-ts#92]
@timostamm 
FromBinary, toBinary works well at typescript side.The uin8Array is from the backed which generate by XXX.toByteArray() in jave code.

It seems that it related to uin8 and int8, XXXX.toByteArray() generate the array in singed int8, however fromBinary need Uin8Array.

By the way, i use the release version 1.0.12.

**Comment by timostamm** [comment]
Hey @hamming 

In Java, `byte` is a signed 8-bit value, meaning that you work with integral values -128 to 127.  
Most languages use an unsigned `byte`, 0 to 255.  

But this difference only matters when you "manually" manipulate byte values.  
If you write a byte array to a file or to a HTTP response using standard facilities, you get the expected binary data. 

The following [example](https://developers.google.com/protocol-buffers/docs/javatutorial#writing-a-message) writes a message to the file system in Java:

```java
// Write the new address book back to disk.
FileOutputStream output = new FileOutputStream(args[0]);
addressBook.build().writeTo(output);
output.close();
```

The written data is conforms to the protobuf binary format and is platform-independant.  
You will be able to read this file with Javascript (using protobuf-ts) without any problems.  
I am not aware of any bugs in the binary format implementation and it has really good test coverage (conformance test suite).

It is most likely that something went wrong on the way from the server side to Javascript. I recommend to dump the data to a file and read it from there, or even log in hexadecimal format and copy the data to a typescript source file. 

This way you can temporarily eliminate the transport from the equation. Once you are sure that the binary data is correct, you will be better equipped to look for the source of the problem.

**Comment by hamming** [comment]
@timostamm 
 Thanks, I made a mistake: I use RSA public key to decrypt binary from server side, and then use the decrypted binary to for protobuf parsing. I ignore the unicode.

Bt the way, It co-works well with java side.

Thanks!

**Comment by timostamm** [comment]
OK, thanks for the feedback and happy coding.
