### ISSUE TITLE
Expose "fetchInit" in RpcOptions to allow sending credentials

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#95]
I'm using https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#grpc-web-transport but I don't know if there is a way to send credentials like in a classic web client:

```ts
initClient({
  baseUrl: "localhost:3000",
  fetchOptions: { credentials: "include" },
});
```

Is it possible or am I totally wrong?

**Comment by frederikhors** [comment]
My [grpc-web server](https://github.com/improbable-eng/grpc-web) doesn't get cookies.

**Comment by frederikhors** [comment]
I think we have some useful hints about this problem: https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web/docs/transport.md.

**Comment by timostamm** [comment]
Why not send credentials / token in a header? 

[rpc-options](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#rpc-options) take metadata, which translate to HTTP headers.

For example:

https://github.com/timostamm/protobuf-ts/blob/a2c34bab05f8c3c50f124d70927e26669b5c1a01/packages/example-chat-system/browser-client/index.ts#L64-L70

Note that CORS applies across domains.

Adding something like "fetchOptions" should be pretty straight-forward to add to the grpc-web and twirp transports.

**Comment by frederikhors** [comment]
Because we are using cookies not readable in browser with Javascript.

**Comment by frederikhors** [comment]
Cookies HTTP-ONLY.

**Comment by timostamm** [comment]
A valid point...

Yes, this should work like improbable-eng. 

The following property should be added to [twirp-options.ts](https://github.com/timostamm/protobuf-ts/blob/master/packages/twirp-transport/src/twirp-options.ts) and [grpc-web-options.ts](https://github.com/timostamm/protobuf-ts/blob/master/packages/grpcweb-transport/src/grpc-web-options.ts):

```typescript
    /**
     * Pass options to fetch API calls. 
     */
    fetchInit?: Exclude<RequestInit, "body" | "headers" | "method" | "signal">;
```

And passed to all fetch calls.

I'm a bit swamped right now. Do you want to open a PR?

**Comment by frederikhors** [comment]
> Do you want to open a PR?

I am not able to. 🤣

**Comment by frederikhors** [comment]
What a pity! This blocks all the plans I had with this library, at least for now.

Do you have a temporary workaround?

**Comment by timostamm** [comment]
> I am not able to. 🤣

Just click fork in the top right, check out your fork and do the changes. 


> Do you have a temporary workaround?

I'd just copy [grpc-web-transport.ts](https://github.com/timostamm/protobuf-ts/blob/master/packages/grpcweb-transport/src/grpc-web-transport.ts) into my project and add the necessary properties to the fetch calls. Maybe you have to copy another file over and add a tsconfig for some settings, but it shouldn't be too difficult.

**Comment by frederikhors** [comment]
> do the changes

This is what I am not able to do. 🤣

**Comment by timostamm** [comment]
Then just copy grpc-web-transport.ts There are only 2 places where fetch() is called

```typescript
        globalThis.fetch(url, {
            method: 'POST',
            headers: createGrpcWebRequestHeader(new globalThis.Headers(), format, opt.deadline, opt.meta),
            body: createGrpcWebRequestBody(inputBytes, format),
            signal: options.abort ?? null, // node-fetch@3.0.0-beta.9 rejects `undefined`
            credentials: 'include'
//          ^^^^^^^^^^^^^^^^^^^^^^
// add this. or maybe 'same-origin', depending on what you need.
        })
```

**Comment by frederikhors** [comment]
@timostamm Yeah, I'm hacking around like this... Thanks!
