### ISSUE TITLE
`npx protoc --ts_out . --proto_path protos protos/msg-readme.proto` File does not reside within any path specified using --proto_path

### ISSUE THREAD

**Issue by ishowman** [timostamm/protobuf-ts#97]
Follow the steps of quickstart, it tells me `File does not reside within any path specified using --proto_path` while running `npx protoc --ts_out . --proto_path protos protos/msg-readme.proto` .

Could you provide a demo repo? I don't know how to specify right path.

**Comment by Bluskript** [comment]
`msg-readme.proto` must be inside of a folder called `protos`, have you tried that?

**Comment by timostamm** [comment]
```bash
mkdir issue97
cd issue97
npm init -y
npm i @protobuf-ts/plugin
mkdir protos
curl https://raw.githubusercontent.com/timostamm/protobuf-ts/master/packages/test-fixtures/msg-readme.proto > protos/msg-readme.proto
```

This creates:

![Bildschirmfoto 2021-04-09 um 12 26 27](https://user-images.githubusercontent.com/4289451/114167094-d1a92280-992e-11eb-9ae0-29d7ba955d35.png)

```bash
npx protoc --ts_out . --proto_path protos protos/msg-readme.proto
```

This generates msg-readme.ts:

![Bildschirmfoto 2021-04-09 um 12 27 21](https://user-images.githubusercontent.com/4289451/114167239-fb624980-992e-11eb-9c92-7e78973a39bf.png)

**Comment by timostamm** [comment]
Quickstart example has been updated. Thanks for the report!
