### ISSUE TITLE
Message type field alway compile as optional

### ISSUE THREAD

**Issue by johnsoncodehk** [timostamm/protobuf-ts#98]
### Steps to reproduce

Compile this proto code:

```proto
syntax = "proto3";

message Person {
    Son sonA = 1;
    optional Son sonB = 2;
}
message Son { }
```

### What is expected?

Person result:

```ts
export interface Person {
    sonA: Son;
    sonB?: Son;
}
```

### What is actually happening?

Person result:

```ts
export interface Person {
    sonA?: Son;
    sonB?: Son;
}
```

**Comment by timostamm** [comment]
Message fields are always optional. 

Consider the following proto: 

```proto
syntax = "proto3";

message Rec {
    Rec child = 1;
}
```

When you create an instance of `Rec`, it would have to allocate recursively. That doesn't work. 

I do wonder why `optional Son sonB = 2;` is valid syntax. It's ambiguous at best.

**Comment by johnsoncodehk** [comment]
> When you create an instance of Rec, it would have to allocate recursively. That doesn't work.

This is invalid in runtime, but this is legal.

Consider this code:

```proto
syntax = "proto3";

message Rec {
    Child child = 1;
}
message Child {
    Rec rec = 1;
}
```

We should not change the compile result to prevent users doing stupid things because we can't.

**Comment by timostamm** [comment]
You propose that a message field without the "optional" label should be required:

```ts
export interface Rec {
    child: Rec;
}
```

What should happen when you create an instance of Rec?

```ts
let rec = Rec.create();
let recChild: Rec = rec.child;
````

The assignment above must be valid, because `rec.child` is of type `Rec`. 

But this is impossible. `Rec.create()` would have to populate the `child` property with a `Rec` instance. And this would have to happen recursively, immediately overflowing your stack.

**Comment by johnsoncodehk** [comment]
I think the compiler should have loop checks and thrown in invalid situations. But not leak the invalidation handle behavior to compile result.

Anyway I understand your consideration and respect your decide, thank you. :)

**Comment by johnsoncodehk** [comment]
Hi @timostamm, sorry for bother again.

I wanted to change this behavior in a special branch for myself, because this is a important request for our project.

Where should start to modify? Any hints would be very helpful, thank you!

**Comment by timostamm** [comment]
> I think the compiler should have loop checks and thrown in invalid situations. 

Do you mean the protobuf compiler `protoc`?  Or `protobuf-ts`, the plugin? 

This .proto is perfectly valid:

```proto
syntax = "proto3";

message Rec {
    Rec child = 1;
}
```

Changing protoc to disallow the recursion would break a lot of existing code.  

Changing protobuf-ts means that it can't handle these .proto files.  
A plugin should be able to work with any valid .proto file (maybe with the exception of proto 1 or 2 syntax).  

I won't be able to give you any support with this, but feel free to [fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)!

**Comment by timostamm** [comment]
I would definitely support an alternative approach: [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate) provides options for validation rules. Having support for these validation rules would be very beneficial. 

For example, the following option makes a message field required:
```proto
  Location home = 4 [(validate.rules).message.required = true];
```

This is runtime validation. You can still create "invalid" messages, but a (to be created) `validate()` function can be used to check the message. 

This can be implemented with reflection, much easier than changing the code generator.

**Comment by johnsoncodehk** [comment]
> Do you mean the protobuf compiler protoc? Or protobuf-ts, the plugin?

I just realized that we might be talking different things.

> Changing protoc to disallow the recursion would break a lot of existing code.

In my mind it just change the output TS interface, I can also use the post-processing script to remove the `?` in output TS interfaces, it should not have any effect to the compiler. But post-processing script will remove all `?` even the field is optional.

> I won't be able to give you any support with this, but feel free to fork!

Of course, I don't want to make unexpected changes to original repo. :)

Thanks for the suggestion for `protoc-gen-validate`, but it may not a feasible to me, because I will to compile some continually updating proto files, and we can't change these proto files source code, it mean I need to add `[(validate.rules).message.required = true]` every time updated.
